package com.synesoft.fisp.app.dp.model;

import java.math.BigDecimal;

public class LoanAmountCheckForm {
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.ID
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.CENSUS_MONTH
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private String censusMonth;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.PRODUCT_CODE
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private String productCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.PRODUCT_NAME
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private String productName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.GL_DR_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private Long glDrCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.GL_DR_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private BigDecimal glDrAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.RPT_GRANT_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private Long rptGrantCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.RTP_GRANT_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private BigDecimal rtpGrantAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.DR_DIFF_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private Long drDiffCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.DR_DIFF_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private BigDecimal drDiffAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.GL_CR_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private Long glCrCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.GL_CR_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private BigDecimal glCrAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.RPT_RPYM_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private Long rptRpymCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.RPT_RPYM_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private BigDecimal rptRpymAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.CR_DIFF_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private Long crDiffCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.CR_DIFF_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private BigDecimal crDiffAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.RSV1
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.RSV2
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.RSV3
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.RSV4
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_AMOUNT_CHECK.RSV5
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.ID
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.ID
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.ID
     *
     * @param id the value for DM_LOAN_AMOUNT_CHECK.ID
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.CENSUS_MONTH
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.CENSUS_MONTH
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public String getCensusMonth() {
        return censusMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.CENSUS_MONTH
     *
     * @param censusMonth the value for DM_LOAN_AMOUNT_CHECK.CENSUS_MONTH
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setCensusMonth(String censusMonth) {
        this.censusMonth = censusMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.PRODUCT_CODE
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.PRODUCT_CODE
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.PRODUCT_CODE
     *
     * @param productCode the value for DM_LOAN_AMOUNT_CHECK.PRODUCT_CODE
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.PRODUCT_NAME
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.PRODUCT_NAME
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.PRODUCT_NAME
     *
     * @param productName the value for DM_LOAN_AMOUNT_CHECK.PRODUCT_NAME
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.GL_DR_COUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.GL_DR_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public Long getGlDrCount() {
        return glDrCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.GL_DR_COUNT
     *
     * @param glDrCount the value for DM_LOAN_AMOUNT_CHECK.GL_DR_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setGlDrCount(Long glDrCount) {
        this.glDrCount = glDrCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.GL_DR_AMOUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.GL_DR_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public BigDecimal getGlDrAmount() {
        return glDrAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.GL_DR_AMOUNT
     *
     * @param glDrAmount the value for DM_LOAN_AMOUNT_CHECK.GL_DR_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setGlDrAmount(BigDecimal glDrAmount) {
        this.glDrAmount = glDrAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.RPT_GRANT_COUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.RPT_GRANT_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public Long getRptGrantCount() {
        return rptGrantCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.RPT_GRANT_COUNT
     *
     * @param rptGrantCount the value for DM_LOAN_AMOUNT_CHECK.RPT_GRANT_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setRptGrantCount(Long rptGrantCount) {
        this.rptGrantCount = rptGrantCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.RTP_GRANT_AMOUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.RTP_GRANT_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public BigDecimal getRtpGrantAmount() {
        return rtpGrantAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.RTP_GRANT_AMOUNT
     *
     * @param rtpGrantAmount the value for DM_LOAN_AMOUNT_CHECK.RTP_GRANT_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setRtpGrantAmount(BigDecimal rtpGrantAmount) {
        this.rtpGrantAmount = rtpGrantAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.DR_DIFF_COUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.DR_DIFF_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public Long getDrDiffCount() {
        return drDiffCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.DR_DIFF_COUNT
     *
     * @param drDiffCount the value for DM_LOAN_AMOUNT_CHECK.DR_DIFF_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setDrDiffCount(Long drDiffCount) {
        this.drDiffCount = drDiffCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.DR_DIFF_AMOUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.DR_DIFF_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public BigDecimal getDrDiffAmount() {
        return drDiffAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.DR_DIFF_AMOUNT
     *
     * @param drDiffAmount the value for DM_LOAN_AMOUNT_CHECK.DR_DIFF_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setDrDiffAmount(BigDecimal drDiffAmount) {
        this.drDiffAmount = drDiffAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.GL_CR_COUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.GL_CR_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public Long getGlCrCount() {
        return glCrCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.GL_CR_COUNT
     *
     * @param glCrCount the value for DM_LOAN_AMOUNT_CHECK.GL_CR_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setGlCrCount(Long glCrCount) {
        this.glCrCount = glCrCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.GL_CR_AMOUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.GL_CR_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public BigDecimal getGlCrAmount() {
        return glCrAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.GL_CR_AMOUNT
     *
     * @param glCrAmount the value for DM_LOAN_AMOUNT_CHECK.GL_CR_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setGlCrAmount(BigDecimal glCrAmount) {
        this.glCrAmount = glCrAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.RPT_RPYM_COUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.RPT_RPYM_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public Long getRptRpymCount() {
        return rptRpymCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.RPT_RPYM_COUNT
     *
     * @param rptRpymCount the value for DM_LOAN_AMOUNT_CHECK.RPT_RPYM_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setRptRpymCount(Long rptRpymCount) {
        this.rptRpymCount = rptRpymCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.RPT_RPYM_AMOUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.RPT_RPYM_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public BigDecimal getRptRpymAmount() {
        return rptRpymAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.RPT_RPYM_AMOUNT
     *
     * @param rptRpymAmount the value for DM_LOAN_AMOUNT_CHECK.RPT_RPYM_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setRptRpymAmount(BigDecimal rptRpymAmount) {
        this.rptRpymAmount = rptRpymAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.CR_DIFF_COUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.CR_DIFF_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public Long getCrDiffCount() {
        return crDiffCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.CR_DIFF_COUNT
     *
     * @param crDiffCount the value for DM_LOAN_AMOUNT_CHECK.CR_DIFF_COUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setCrDiffCount(Long crDiffCount) {
        this.crDiffCount = crDiffCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.CR_DIFF_AMOUNT
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.CR_DIFF_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public BigDecimal getCrDiffAmount() {
        return crDiffAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.CR_DIFF_AMOUNT
     *
     * @param crDiffAmount the value for DM_LOAN_AMOUNT_CHECK.CR_DIFF_AMOUNT
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setCrDiffAmount(BigDecimal crDiffAmount) {
        this.crDiffAmount = crDiffAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.RSV1
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.RSV1
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.RSV1
     *
     * @param rsv1 the value for DM_LOAN_AMOUNT_CHECK.RSV1
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.RSV2
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.RSV2
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.RSV2
     *
     * @param rsv2 the value for DM_LOAN_AMOUNT_CHECK.RSV2
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.RSV3
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.RSV3
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.RSV3
     *
     * @param rsv3 the value for DM_LOAN_AMOUNT_CHECK.RSV3
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.RSV4
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.RSV4
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.RSV4
     *
     * @param rsv4 the value for DM_LOAN_AMOUNT_CHECK.RSV4
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_AMOUNT_CHECK.RSV5
     *
     * @return the value of DM_LOAN_AMOUNT_CHECK.RSV5
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_AMOUNT_CHECK.RSV5
     *
     * @param rsv5 the value for DM_LOAN_AMOUNT_CHECK.RSV5
     *
     * @abatorgenerated Tue Oct 08 18:30:01 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
}
