package com.synesoft.fisp.app.dp.model;

import java.math.BigDecimal;

public class LoanBalanceCheckForm {
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.ID
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.PRODUCT_CODE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private String productCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.CENSUS_MONTH
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private String censusMonth;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.PRODUCT_NAME
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private String productName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.GL_COUNT
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private Long glCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.GL_BALANCE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private BigDecimal glBalance;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.APPLICATION_COUNT
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private Long applicationCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.APPLICATION_BALANCE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private BigDecimal applicationBalance;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.DIFFERENCE_COUNT
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private Long differenceCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.DIFFERENCE_BALANCE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private BigDecimal differenceBalance;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.RSV1
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.RSV2
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.RSV3
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.RSV4
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DM_LOAN_BALANCE_CHECK.RSV5
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.ID
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.ID
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.ID
     *
     * @param id the value for DM_LOAN_BALANCE_CHECK.ID
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.PRODUCT_CODE
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.PRODUCT_CODE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.PRODUCT_CODE
     *
     * @param productCode the value for DM_LOAN_BALANCE_CHECK.PRODUCT_CODE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.CENSUS_MONTH
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.CENSUS_MONTH
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public String getCensusMonth() {
        return censusMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.CENSUS_MONTH
     *
     * @param censusMonth the value for DM_LOAN_BALANCE_CHECK.CENSUS_MONTH
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setCensusMonth(String censusMonth) {
        this.censusMonth = censusMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.PRODUCT_NAME
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.PRODUCT_NAME
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.PRODUCT_NAME
     *
     * @param productName the value for DM_LOAN_BALANCE_CHECK.PRODUCT_NAME
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.GL_COUNT
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.GL_COUNT
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public Long getGlCount() {
        return glCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.GL_COUNT
     *
     * @param glCount the value for DM_LOAN_BALANCE_CHECK.GL_COUNT
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setGlCount(Long glCount) {
        this.glCount = glCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.GL_BALANCE
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.GL_BALANCE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public BigDecimal getGlBalance() {
        return glBalance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.GL_BALANCE
     *
     * @param glBalance the value for DM_LOAN_BALANCE_CHECK.GL_BALANCE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setGlBalance(BigDecimal glBalance) {
        this.glBalance = glBalance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.APPLICATION_COUNT
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.APPLICATION_COUNT
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public Long getApplicationCount() {
        return applicationCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.APPLICATION_COUNT
     *
     * @param applicationCount the value for DM_LOAN_BALANCE_CHECK.APPLICATION_COUNT
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setApplicationCount(Long applicationCount) {
        this.applicationCount = applicationCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.APPLICATION_BALANCE
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.APPLICATION_BALANCE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public BigDecimal getApplicationBalance() {
        return applicationBalance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.APPLICATION_BALANCE
     *
     * @param applicationBalance the value for DM_LOAN_BALANCE_CHECK.APPLICATION_BALANCE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setApplicationBalance(BigDecimal applicationBalance) {
        this.applicationBalance = applicationBalance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.DIFFERENCE_COUNT
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.DIFFERENCE_COUNT
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public Long getDifferenceCount() {
        return differenceCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.DIFFERENCE_COUNT
     *
     * @param differenceCount the value for DM_LOAN_BALANCE_CHECK.DIFFERENCE_COUNT
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setDifferenceCount(Long differenceCount) {
        this.differenceCount = differenceCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.DIFFERENCE_BALANCE
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.DIFFERENCE_BALANCE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public BigDecimal getDifferenceBalance() {
        return differenceBalance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.DIFFERENCE_BALANCE
     *
     * @param differenceBalance the value for DM_LOAN_BALANCE_CHECK.DIFFERENCE_BALANCE
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setDifferenceBalance(BigDecimal differenceBalance) {
        this.differenceBalance = differenceBalance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.RSV1
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.RSV1
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.RSV1
     *
     * @param rsv1 the value for DM_LOAN_BALANCE_CHECK.RSV1
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.RSV2
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.RSV2
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.RSV2
     *
     * @param rsv2 the value for DM_LOAN_BALANCE_CHECK.RSV2
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.RSV3
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.RSV3
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.RSV3
     *
     * @param rsv3 the value for DM_LOAN_BALANCE_CHECK.RSV3
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.RSV4
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.RSV4
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.RSV4
     *
     * @param rsv4 the value for DM_LOAN_BALANCE_CHECK.RSV4
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DM_LOAN_BALANCE_CHECK.RSV5
     *
     * @return the value of DM_LOAN_BALANCE_CHECK.RSV5
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DM_LOAN_BALANCE_CHECK.RSV5
     *
     * @param rsv5 the value for DM_LOAN_BALANCE_CHECK.RSV5
     *
     * @abatorgenerated Tue Oct 08 14:40:31 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
}
