package com.synesoft.sysrunner.domain.model;

import java.math.BigDecimal;

import org.hibernate.validator.constraints.NotEmpty;

import com.synesoft.sysrunner.app.BatchManage.model.BatchManageForm.BMG_STEP_Add;


public class BatStepInfo extends BatStepInfoKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_INFO.STEP_NAME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
	@NotEmpty(groups = { BMG_STEP_Add.class}, message = "{e.bm.0007}")
    private String stepName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_INFO.STEP_START_TYPE
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
	@NotEmpty(groups = { BMG_STEP_Add.class}, message = "{e.bm.0010}")
    private String stepStartType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_INFO.STEP_START_DAY
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private Short stepStartDay;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_INFO.SUB_STEP_NUM
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private Integer subStepNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_INFO.STEP_COMMAND
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    @NotEmpty(groups = { BMG_STEP_Add.class}, message = "{e.sysrunner.0020}")
    private String stepCommand;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_INFO.STEP_ENABLE
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    @NotEmpty(groups = { BMG_STEP_Add.class}, message = "{e.bm.0008}")
    private String stepEnable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_INFO.PRIORITY
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private BigDecimal priority;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_INFO.ALLOW_SKIP
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    @NotEmpty(groups = { BMG_STEP_Add.class}, message = "{e.sysrunner.0018}")
    private String allowSkip;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_INFO.AUTO_SKIP
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    @NotEmpty(groups = { BMG_STEP_Add.class}, message = "{e.sysrunner.0019}")
    private String autoSkip;
    
    private String taskName;
    
    private String dpCfgType;
    
    private String dpCfgId;
    
    private String dpCfgName;
    
    public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_INFO.STEP_NAME
     *
     * @return the value of BAT_STEP_INFO.STEP_NAME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getStepName() {
        return stepName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_INFO.STEP_NAME
     *
     * @param stepName the value for BAT_STEP_INFO.STEP_NAME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setStepName(String stepName) {
        this.stepName = stepName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_INFO.STEP_START_TYPE
     *
     * @return the value of BAT_STEP_INFO.STEP_START_TYPE
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getStepStartType() {
        return stepStartType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_INFO.STEP_START_TYPE
     *
     * @param stepStartType the value for BAT_STEP_INFO.STEP_START_TYPE
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setStepStartType(String stepStartType) {
        this.stepStartType = stepStartType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_INFO.STEP_START_DAY
     *
     * @return the value of BAT_STEP_INFO.STEP_START_DAY
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public Short getStepStartDay() {
        return stepStartDay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_INFO.STEP_START_DAY
     *
     * @param stepStartDay the value for BAT_STEP_INFO.STEP_START_DAY
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setStepStartDay(Short stepStartDay) {
        this.stepStartDay = stepStartDay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_INFO.SUB_STEP_NUM
     *
     * @return the value of BAT_STEP_INFO.SUB_STEP_NUM
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public Integer getSubStepNum() {
        return subStepNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_INFO.SUB_STEP_NUM
     *
     * @param subStepNum the value for BAT_STEP_INFO.SUB_STEP_NUM
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setSubStepNum(Integer subStepNum) {
        this.subStepNum = subStepNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_INFO.STEP_COMMAND
     *
     * @return the value of BAT_STEP_INFO.STEP_COMMAND
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getStepCommand() {
        return stepCommand;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_INFO.STEP_COMMAND
     *
     * @param stepCommand the value for BAT_STEP_INFO.STEP_COMMAND
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setStepCommand(String stepCommand) {
        this.stepCommand = stepCommand;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_INFO.STEP_ENABLE
     *
     * @return the value of BAT_STEP_INFO.STEP_ENABLE
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getStepEnable() {
        return stepEnable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_INFO.STEP_ENABLE
     *
     * @param stepEnable the value for BAT_STEP_INFO.STEP_ENABLE
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setStepEnable(String stepEnable) {
        this.stepEnable = stepEnable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_INFO.PRIORITY
     *
     * @return the value of BAT_STEP_INFO.PRIORITY
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public BigDecimal getPriority() {
        return priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_INFO.PRIORITY
     *
     * @param priority the value for BAT_STEP_INFO.PRIORITY
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_INFO.ALLOW_SKIP
     *
     * @return the value of BAT_STEP_INFO.ALLOW_SKIP
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getAllowSkip() {
        return allowSkip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_INFO.ALLOW_SKIP
     *
     * @param allowSkip the value for BAT_STEP_INFO.ALLOW_SKIP
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setAllowSkip(String allowSkip) {
        this.allowSkip = allowSkip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_INFO.AUTO_SKIP
     *
     * @return the value of BAT_STEP_INFO.AUTO_SKIP
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getAutoSkip() {
        return autoSkip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_INFO.AUTO_SKIP
     *
     * @param autoSkip the value for BAT_STEP_INFO.AUTO_SKIP
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setAutoSkip(String autoSkip) {
        this.autoSkip = autoSkip;
    }

	public String getDpCfgType() {
		return dpCfgType;
	}

	public void setDpCfgType(String dpCfgType) {
		this.dpCfgType = dpCfgType;
	}

	public String getDpCfgId() {
		return dpCfgId;
	}

	public void setDpCfgId(String dpCfgId) {
		this.dpCfgId = dpCfgId;
	}

	public String getDpCfgName() {
		return dpCfgName;
	}

	public void setDpCfgName(String dpCfgName) {
		this.dpCfgName = dpCfgName;
	}
    
}