package com.synesoft.sysrunner.domain.model;

import java.math.BigDecimal;

public class BatSubstepRtm extends BatSubstepRtmKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_SUBSTEP_RTM.MACHINE_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private Short machineId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_SUBSTEP_RTM.PID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private BigDecimal pid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_SUBSTEP_RTM.RUN_STATUS
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private String runStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_SUBSTEP_RTM.PRIORITY
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private BigDecimal priority;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_SUBSTEP_RTM.COMMIT_POINT
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private String commitPoint;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_SUBSTEP_RTM.READY_TIME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private String readyTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_SUBSTEP_RTM.START_TIME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private String startTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_SUBSTEP_RTM.END_TIME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private String endTime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_SUBSTEP_RTM.MACHINE_ID
     *
     * @return the value of BAT_SUBSTEP_RTM.MACHINE_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public Short getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_SUBSTEP_RTM.MACHINE_ID
     *
     * @param machineId the value for BAT_SUBSTEP_RTM.MACHINE_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setMachineId(Short machineId) {
        this.machineId = machineId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_SUBSTEP_RTM.PID
     *
     * @return the value of BAT_SUBSTEP_RTM.PID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public BigDecimal getPid() {
        return pid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_SUBSTEP_RTM.PID
     *
     * @param pid the value for BAT_SUBSTEP_RTM.PID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setPid(BigDecimal pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_SUBSTEP_RTM.RUN_STATUS
     *
     * @return the value of BAT_SUBSTEP_RTM.RUN_STATUS
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_SUBSTEP_RTM.RUN_STATUS
     *
     * @param runStatus the value for BAT_SUBSTEP_RTM.RUN_STATUS
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setRunStatus(String runStatus) {
        this.runStatus = runStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_SUBSTEP_RTM.PRIORITY
     *
     * @return the value of BAT_SUBSTEP_RTM.PRIORITY
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public BigDecimal getPriority() {
        return priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_SUBSTEP_RTM.PRIORITY
     *
     * @param priority the value for BAT_SUBSTEP_RTM.PRIORITY
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_SUBSTEP_RTM.COMMIT_POINT
     *
     * @return the value of BAT_SUBSTEP_RTM.COMMIT_POINT
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getCommitPoint() {
        return commitPoint;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_SUBSTEP_RTM.COMMIT_POINT
     *
     * @param commitPoint the value for BAT_SUBSTEP_RTM.COMMIT_POINT
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setCommitPoint(String commitPoint) {
        this.commitPoint = commitPoint;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_SUBSTEP_RTM.READY_TIME
     *
     * @return the value of BAT_SUBSTEP_RTM.READY_TIME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getReadyTime() {
        return readyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_SUBSTEP_RTM.READY_TIME
     *
     * @param readyTime the value for BAT_SUBSTEP_RTM.READY_TIME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setReadyTime(String readyTime) {
        this.readyTime = readyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_SUBSTEP_RTM.START_TIME
     *
     * @return the value of BAT_SUBSTEP_RTM.START_TIME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_SUBSTEP_RTM.START_TIME
     *
     * @param startTime the value for BAT_SUBSTEP_RTM.START_TIME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_SUBSTEP_RTM.END_TIME
     *
     * @return the value of BAT_SUBSTEP_RTM.END_TIME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_SUBSTEP_RTM.END_TIME
     *
     * @param endTime the value for BAT_SUBSTEP_RTM.END_TIME
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
}