package com.synesoft.fisp.domain.model;

public class DpExprMethod {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_METHOD.M_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String mId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_METHOD.CLASS_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String className;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_METHOD.METHOD_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String methodName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_METHOD.METHOD_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String methodDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_METHOD.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_METHOD.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_METHOD.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv3;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_METHOD.M_ID
     *
     * @return the value of DP_EXPR_METHOD.M_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getmId() {
        return mId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_METHOD.M_ID
     *
     * @param mId the value for DP_EXPR_METHOD.M_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setmId(String mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_METHOD.CLASS_NAME
     *
     * @return the value of DP_EXPR_METHOD.CLASS_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_METHOD.CLASS_NAME
     *
     * @param className the value for DP_EXPR_METHOD.CLASS_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_METHOD.METHOD_NAME
     *
     * @return the value of DP_EXPR_METHOD.METHOD_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_METHOD.METHOD_NAME
     *
     * @param methodName the value for DP_EXPR_METHOD.METHOD_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_METHOD.METHOD_DESC
     *
     * @return the value of DP_EXPR_METHOD.METHOD_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getMethodDesc() {
        return methodDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_METHOD.METHOD_DESC
     *
     * @param methodDesc the value for DP_EXPR_METHOD.METHOD_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setMethodDesc(String methodDesc) {
        this.methodDesc = methodDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_METHOD.RSV1
     *
     * @return the value of DP_EXPR_METHOD.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_METHOD.RSV1
     *
     * @param rsv1 the value for DP_EXPR_METHOD.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_METHOD.RSV2
     *
     * @return the value of DP_EXPR_METHOD.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_METHOD.RSV2
     *
     * @param rsv2 the value for DP_EXPR_METHOD.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_METHOD.RSV3
     *
     * @return the value of DP_EXPR_METHOD.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_METHOD.RSV3
     *
     * @param rsv3 the value for DP_EXPR_METHOD.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }
}