package com.synesoft.fisp.domain.model;


import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.synesoft.fisp.app.common.validation.NotEmptyEx;
import com.synesoft.fisp.app.dp.model.DpFileMdfForm.DpFileMdfFormMdf;
import com.synesoft.fisp.app.dp.model.DpImpAddForm.DpImpAddFormAdd;
import com.synesoft.fisp.app.dp.model.DpImpCfgForm.DpImpCfgFormInit;
import com.synesoft.fisp.app.dp.model.DpImpCfgForm.DpImpCfgFormSubmit;
import com.synesoft.fisp.app.dp.model.DpImpDtlForm.DpImpDtlFormInit;
import com.synesoft.fisp.app.dp.model.DpImpQryForm.DpImpQryFormDel;
import com.synesoft.fisp.app.dp.model.DpImpUptForm.DpImpUptFormInit;

public class DpImpCfg {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.IMP_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@NotEmpty(groups = {DpImpQryFormDel.class, DpImpDtlFormInit.class, DpImpUptFormInit.class, 
			DpImpCfgFormInit.class, DpFileMdfFormMdf.class, DpImpCfgFormSubmit.class }, message ="{e.dp.imp.0001}")
    private String impId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.PROJ_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@NotEmptyEx(groups = {DpImpAddFormAdd.class }, message ="{e.dp.imp.0013}")
	@Size(groups = {DpImpAddFormAdd.class, DpFileMdfFormMdf.class }, min = 0, max = 32, message = "{e.dp.imp.0063}")
    private String projId;

    /** 
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.BRANCH_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@NotEmpty(groups = {DpImpAddFormAdd.class }, message ="{e.dp.imp.0014}")
	@Size(groups = {DpImpAddFormAdd.class, DpFileMdfFormMdf.class }, min = 0, max = 20, message = "{e.dp.imp.0064}")
    private String branchId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.BATCH_NO
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@NotNull(groups = {DpImpAddFormAdd.class }, message ="{e.dp.imp.0015}")
	@Max(groups = {DpImpAddFormAdd.class, DpFileMdfFormMdf.class },  message = "{e.dp.imp.0065}", value = 999999999)
    private Long batchNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.SEQ_NO
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@NotNull(groups = {DpImpAddFormAdd.class }, message ="{e.dp.imp.0016}")
	@Max(groups = {DpImpAddFormAdd.class, DpFileMdfFormMdf.class }, value = 999, message = "{e.dp.imp.0066}")
    private Short seqNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.TABLE_NAME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@NotEmpty(groups = {DpImpAddFormAdd.class }, message ="{e.dp.imp.0018}")
	@Size(groups = {DpImpAddFormAdd.class, DpFileMdfFormMdf.class }, min = 0, max = 128, message = "{e.dp.imp.0067}")
    private String tableName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.FILE_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String fileId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.FILE_NAME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@NotEmpty(groups = {DpImpAddFormAdd.class }, message ="{e.dp.imp.0017}")
	@Size(groups = {DpImpAddFormAdd.class, DpFileMdfFormMdf.class }, min = 0, max = 128, message = "{e.dp.imp.0068}")
    private String fileName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.FILE_PATH
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@NotEmpty(groups = {DpImpAddFormAdd.class }, message ="{e.dp.imp.0019}")
	@Size(groups = {DpImpAddFormAdd.class, DpFileMdfFormMdf.class }, min = 0, max = 128, message = "{e.dp.imp.0069}")
    private String filePath;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.MAND_FLAG
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@NotEmpty(groups = {DpImpAddFormAdd.class }, message ="{e.dp.imp.0020}")
	@Size(groups = {DpImpAddFormAdd.class, DpFileMdfFormMdf.class }, min = 0, max = 1, message = "{e.dp.imp.0070}")
    private String mandFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.COMMENTS
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
	@Size(groups = {DpImpAddFormAdd.class, DpFileMdfFormMdf.class }, min = 0, max = 255, message = "{e.dp.imp.0071}")
    private String comments;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.CREATE_TIME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.CREATE_USER
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.UPDATE_TIME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String updateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.UPDATE_USER
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String updateUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.RSV1
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.RSV2
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.RSV3
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.RSV4
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_CFG.RSV5
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.IMP_ID
     *
     * @return the value of DP_IMP_CFG.IMP_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getImpId() {
        return impId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.IMP_ID
     *
     * @param impId the value for DP_IMP_CFG.IMP_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setImpId(String impId) {
        this.impId = impId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.PROJ_ID
     *
     * @return the value of DP_IMP_CFG.PROJ_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.PROJ_ID
     *
     * @param projId the value for DP_IMP_CFG.PROJ_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setProjId(String projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.BRANCH_ID
     *
     * @return the value of DP_IMP_CFG.BRANCH_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.BRANCH_ID
     *
     * @param branchId the value for DP_IMP_CFG.BRANCH_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.BATCH_NO
     *
     * @return the value of DP_IMP_CFG.BATCH_NO
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public Long getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.BATCH_NO
     *
     * @param batchNo the value for DP_IMP_CFG.BATCH_NO
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setBatchNo(Long batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.SEQ_NO
     *
     * @return the value of DP_IMP_CFG.SEQ_NO
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public Short getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.SEQ_NO
     *
     * @param seqNo the value for DP_IMP_CFG.SEQ_NO
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setSeqNo(Short seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.TABLE_NAME
     *
     * @return the value of DP_IMP_CFG.TABLE_NAME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.TABLE_NAME
     *
     * @param tableName the value for DP_IMP_CFG.TABLE_NAME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.FILE_ID
     *
     * @return the value of DP_IMP_CFG.FILE_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.FILE_ID
     *
     * @param fileId the value for DP_IMP_CFG.FILE_ID
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.FILE_NAME
     *
     * @return the value of DP_IMP_CFG.FILE_NAME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.FILE_NAME
     *
     * @param fileName the value for DP_IMP_CFG.FILE_NAME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.FILE_PATH
     *
     * @return the value of DP_IMP_CFG.FILE_PATH
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.FILE_PATH
     *
     * @param filePath the value for DP_IMP_CFG.FILE_PATH
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.MAND_FLAG
     *
     * @return the value of DP_IMP_CFG.MAND_FLAG
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getMandFlag() {
        return mandFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.MAND_FLAG
     *
     * @param mandFlag the value for DP_IMP_CFG.MAND_FLAG
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setMandFlag(String mandFlag) {
        this.mandFlag = mandFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.COMMENTS
     *
     * @return the value of DP_IMP_CFG.COMMENTS
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.COMMENTS
     *
     * @param comments the value for DP_IMP_CFG.COMMENTS
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.CREATE_TIME
     *
     * @return the value of DP_IMP_CFG.CREATE_TIME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.CREATE_TIME
     *
     * @param createTime the value for DP_IMP_CFG.CREATE_TIME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.CREATE_USER
     *
     * @return the value of DP_IMP_CFG.CREATE_USER
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.CREATE_USER
     *
     * @param createUser the value for DP_IMP_CFG.CREATE_USER
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.UPDATE_TIME
     *
     * @return the value of DP_IMP_CFG.UPDATE_TIME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.UPDATE_TIME
     *
     * @param updateTime the value for DP_IMP_CFG.UPDATE_TIME
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.UPDATE_USER
     *
     * @return the value of DP_IMP_CFG.UPDATE_USER
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.UPDATE_USER
     *
     * @param updateUser the value for DP_IMP_CFG.UPDATE_USER
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.RSV1
     *
     * @return the value of DP_IMP_CFG.RSV1
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.RSV1
     *
     * @param rsv1 the value for DP_IMP_CFG.RSV1
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.RSV2
     *
     * @return the value of DP_IMP_CFG.RSV2
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.RSV2
     *
     * @param rsv2 the value for DP_IMP_CFG.RSV2
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.RSV3
     *
     * @return the value of DP_IMP_CFG.RSV3
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.RSV3
     *
     * @param rsv3 the value for DP_IMP_CFG.RSV3
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.RSV4
     *
     * @return the value of DP_IMP_CFG.RSV4
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.RSV4
     *
     * @param rsv4 the value for DP_IMP_CFG.RSV4
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_CFG.RSV5
     *
     * @return the value of DP_IMP_CFG.RSV5
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_CFG.RSV5
     *
     * @param rsv5 the value for DP_IMP_CFG.RSV5
     *
     * @abatorgenerated Mon Nov 11 15:55:49 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
    
}