package com.synesoft.fisp.domain.model;

public class DpImpLog {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.IMP_LOG_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String impLogId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.IMP_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String impId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.WORK_DATE
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String workDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.PROJ_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String projId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.BRANCH_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String branchId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.BATCH_NO
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private Long batchNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.SEQ_NO
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private Short seqNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.FILE_NAME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String fileName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.TABLE_NAME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String tableName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.IMP_RESULT
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String impResult;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.TOTAL_ROWS
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private Long totalRows;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.ERR_ROWS
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private Long errRows;
    
    private Long errInfo;


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.BEGIN_TIME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String beginTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.END_TIME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String endTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.RSV1
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.RSV2
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.RSV3
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.RSV4
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_IMP_LOG.RSV5
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.IMP_LOG_ID
     *
     * @return the value of DP_IMP_LOG.IMP_LOG_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getImpLogId() {
        return impLogId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.IMP_LOG_ID
     *
     * @param impLogId the value for DP_IMP_LOG.IMP_LOG_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setImpLogId(String impLogId) {
        this.impLogId = impLogId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.IMP_ID
     *
     * @return the value of DP_IMP_LOG.IMP_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getImpId() {
        return impId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.IMP_ID
     *
     * @param impId the value for DP_IMP_LOG.IMP_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setImpId(String impId) {
        this.impId = impId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.WORK_DATE
     *
     * @return the value of DP_IMP_LOG.WORK_DATE
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.WORK_DATE
     *
     * @param workDate the value for DP_IMP_LOG.WORK_DATE
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setWorkDate(String workDate) {
        this.workDate = workDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.PROJ_ID
     *
     * @return the value of DP_IMP_LOG.PROJ_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.PROJ_ID
     *
     * @param projId the value for DP_IMP_LOG.PROJ_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setProjId(String projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.BRANCH_ID
     *
     * @return the value of DP_IMP_LOG.BRANCH_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.BRANCH_ID
     *
     * @param branchId the value for DP_IMP_LOG.BRANCH_ID
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.BATCH_NO
     *
     * @return the value of DP_IMP_LOG.BATCH_NO
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public Long getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.BATCH_NO
     *
     * @param batchNo the value for DP_IMP_LOG.BATCH_NO
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setBatchNo(Long batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.SEQ_NO
     *
     * @return the value of DP_IMP_LOG.SEQ_NO
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public Short getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.SEQ_NO
     *
     * @param seqNo the value for DP_IMP_LOG.SEQ_NO
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setSeqNo(Short seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.FILE_NAME
     *
     * @return the value of DP_IMP_LOG.FILE_NAME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.FILE_NAME
     *
     * @param fileName the value for DP_IMP_LOG.FILE_NAME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.TABLE_NAME
     *
     * @return the value of DP_IMP_LOG.TABLE_NAME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.TABLE_NAME
     *
     * @param tableName the value for DP_IMP_LOG.TABLE_NAME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.IMP_RESULT
     *
     * @return the value of DP_IMP_LOG.IMP_RESULT
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getImpResult() {
        return impResult;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.IMP_RESULT
     *
     * @param impResult the value for DP_IMP_LOG.IMP_RESULT
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setImpResult(String impResult) {
        this.impResult = impResult;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.TOTAL_ROWS
     *
     * @return the value of DP_IMP_LOG.TOTAL_ROWS
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public Long getTotalRows() {
        return totalRows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.TOTAL_ROWS
     *
     * @param totalRows the value for DP_IMP_LOG.TOTAL_ROWS
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setTotalRows(Long totalRows) {
        this.totalRows = totalRows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.ERR_ROWS
     *
     * @return the value of DP_IMP_LOG.ERR_ROWS
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public Long getErrRows() {
        return errRows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.ERR_ROWS
     *
     * @param errRows the value for DP_IMP_LOG.ERR_ROWS
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setErrRows(Long errRows) {
        this.errRows = errRows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.BEGIN_TIME
     *
     * @return the value of DP_IMP_LOG.BEGIN_TIME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.BEGIN_TIME
     *
     * @param beginTime the value for DP_IMP_LOG.BEGIN_TIME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.END_TIME
     *
     * @return the value of DP_IMP_LOG.END_TIME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.END_TIME
     *
     * @param endTime the value for DP_IMP_LOG.END_TIME
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.RSV1
     *
     * @return the value of DP_IMP_LOG.RSV1
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.RSV1
     *
     * @param rsv1 the value for DP_IMP_LOG.RSV1
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.RSV2
     *
     * @return the value of DP_IMP_LOG.RSV2
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.RSV2
     *
     * @param rsv2 the value for DP_IMP_LOG.RSV2
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.RSV3
     *
     * @return the value of DP_IMP_LOG.RSV3
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.RSV3
     *
     * @param rsv3 the value for DP_IMP_LOG.RSV3
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.RSV4
     *
     * @return the value of DP_IMP_LOG.RSV4
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.RSV4
     *
     * @param rsv4 the value for DP_IMP_LOG.RSV4
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_IMP_LOG.RSV5
     *
     * @return the value of DP_IMP_LOG.RSV5
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_IMP_LOG.RSV5
     *
     * @param rsv5 the value for DP_IMP_LOG.RSV5
     *
     * @abatorgenerated Mon Dec 16 14:53:52 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }

	public Long getErrInfo() {
		return errInfo;
	}

	public void setErrInfo(Long errInfo) {
		this.errInfo = errInfo;
	}
    
}