package com.synesoft.fisp.domain.model;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

import com.synesoft.fisp.app.dp.model.DP_Mpp_AddForm.DP_Mpp_Add;
import com.synesoft.fisp.app.dp.model.DP_Mpp_UptForm.DP_Mpp_Upt_Submit;

public class DpMppCfg {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.MPP_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String mppId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.PROJ_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    @NotEmpty(groups = {DP_Mpp_Add.class,DP_Mpp_Upt_Submit.class}, message ="{e.ifc.1002}")
    private String projId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.BRANCH_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    @NotEmpty(groups = {DP_Mpp_Add.class,DP_Mpp_Upt_Submit.class}, message ="{e.de.2002}")
    private String branchId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.BATCH_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    @NotNull(groups = {DP_Mpp_Add.class,DP_Mpp_Upt_Submit.class}, message ="{e.ifc.1004}")
    private Long batchNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.SEQ_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    @NotNull(groups = {DP_Mpp_Add.class,DP_Mpp_Upt_Submit.class}, message ="{e.ifc.1006}")
    private Short seqNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.DEST_TABLE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String destTable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.SRC_TABLE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String srcTable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.PROC_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    @NotEmpty(groups = {DP_Mpp_Add.class,DP_Mpp_Upt_Submit.class}, message ="{e.de.2005}")
    private String procType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.PROC_CFG
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String procCfg;
    
    private String procCfg_key;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.DUP_PROC_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String dupProcType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.ERR_PROC_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String errProcType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.MPP_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    @NotEmpty(groups = {DP_Mpp_Add.class,DP_Mpp_Upt_Submit.class}, message ="{e.dp.valid.002}")
    private String mppName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String comments;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.CREATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.CREATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.UPDATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String updateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.UPDATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String updateUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_MPP_CFG.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.MPP_ID
     *
     * @return the value of DP_MPP_CFG.MPP_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getMppId() {
        return mppId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.MPP_ID
     *
     * @param mppId the value for DP_MPP_CFG.MPP_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setMppId(String mppId) {
        this.mppId = mppId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.PROJ_ID
     *
     * @return the value of DP_MPP_CFG.PROJ_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.PROJ_ID
     *
     * @param projId the value for DP_MPP_CFG.PROJ_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setProjId(String projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.BRANCH_ID
     *
     * @return the value of DP_MPP_CFG.BRANCH_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.BRANCH_ID
     *
     * @param branchId the value for DP_MPP_CFG.BRANCH_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.BATCH_NO
     *
     * @return the value of DP_MPP_CFG.BATCH_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public Long getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.BATCH_NO
     *
     * @param batchNo the value for DP_MPP_CFG.BATCH_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setBatchNo(Long batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.SEQ_NO
     *
     * @return the value of DP_MPP_CFG.SEQ_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public Short getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.SEQ_NO
     *
     * @param seqNo the value for DP_MPP_CFG.SEQ_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setSeqNo(Short seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.DEST_TABLE
     *
     * @return the value of DP_MPP_CFG.DEST_TABLE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getDestTable() {
        return destTable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.DEST_TABLE
     *
     * @param destTable the value for DP_MPP_CFG.DEST_TABLE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setDestTable(String destTable) {
        this.destTable = destTable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.SRC_TABLE
     *
     * @return the value of DP_MPP_CFG.SRC_TABLE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getSrcTable() {
        return srcTable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.SRC_TABLE
     *
     * @param srcTable the value for DP_MPP_CFG.SRC_TABLE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setSrcTable(String srcTable) {
        this.srcTable = srcTable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.PROC_TYPE
     *
     * @return the value of DP_MPP_CFG.PROC_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getProcType() {
        return procType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.PROC_TYPE
     *
     * @param procType the value for DP_MPP_CFG.PROC_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setProcType(String procType) {
        this.procType = procType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.PROC_CFG
     *
     * @return the value of DP_MPP_CFG.PROC_CFG
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getProcCfg() {
        return procCfg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.PROC_CFG
     *
     * @param procCfg the value for DP_MPP_CFG.PROC_CFG
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setProcCfg(String procCfg) {
        this.procCfg = procCfg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.DUP_PROC_TYPE
     *
     * @return the value of DP_MPP_CFG.DUP_PROC_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getDupProcType() {
        return dupProcType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.DUP_PROC_TYPE
     *
     * @param dupProcType the value for DP_MPP_CFG.DUP_PROC_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setDupProcType(String dupProcType) {
        this.dupProcType = dupProcType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.ERR_PROC_TYPE
     *
     * @return the value of DP_MPP_CFG.ERR_PROC_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getErrProcType() {
        return errProcType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.ERR_PROC_TYPE
     *
     * @param errProcType the value for DP_MPP_CFG.ERR_PROC_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setErrProcType(String errProcType) {
        this.errProcType = errProcType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.MPP_NAME
     *
     * @return the value of DP_MPP_CFG.MPP_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getMppName() {
        return mppName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.MPP_NAME
     *
     * @param mppName the value for DP_MPP_CFG.MPP_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setMppName(String mppName) {
        this.mppName = mppName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.COMMENTS
     *
     * @return the value of DP_MPP_CFG.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.COMMENTS
     *
     * @param comments the value for DP_MPP_CFG.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.CREATE_TIME
     *
     * @return the value of DP_MPP_CFG.CREATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.CREATE_TIME
     *
     * @param createTime the value for DP_MPP_CFG.CREATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.CREATE_USER
     *
     * @return the value of DP_MPP_CFG.CREATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.CREATE_USER
     *
     * @param createUser the value for DP_MPP_CFG.CREATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.UPDATE_TIME
     *
     * @return the value of DP_MPP_CFG.UPDATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.UPDATE_TIME
     *
     * @param updateTime the value for DP_MPP_CFG.UPDATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.UPDATE_USER
     *
     * @return the value of DP_MPP_CFG.UPDATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.UPDATE_USER
     *
     * @param updateUser the value for DP_MPP_CFG.UPDATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.RSV1
     *
     * @return the value of DP_MPP_CFG.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.RSV1
     *
     * @param rsv1 the value for DP_MPP_CFG.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.RSV2
     *
     * @return the value of DP_MPP_CFG.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.RSV2
     *
     * @param rsv2 the value for DP_MPP_CFG.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.RSV3
     *
     * @return the value of DP_MPP_CFG.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.RSV3
     *
     * @param rsv3 the value for DP_MPP_CFG.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.RSV4
     *
     * @return the value of DP_MPP_CFG.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.RSV4
     *
     * @param rsv4 the value for DP_MPP_CFG.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_MPP_CFG.RSV5
     *
     * @return the value of DP_MPP_CFG.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_MPP_CFG.RSV5
     *
     * @param rsv5 the value for DP_MPP_CFG.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:53 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }

	public String getProcCfg_key() {
		return procCfg_key;
	}

	public void setProcCfg_key(String procCfg_key) {
		this.procCfg_key = procCfg_key;
	}

}