package com.synesoft.fisp.domain.model;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.synesoft.fisp.app.dp.model.DpTableAddForm.DpTableAddFormAdd;
import com.synesoft.fisp.app.dp.model.DpTableDtlForm.DpTableDtlFormInit;
import com.synesoft.fisp.app.dp.model.DpTableMdfForm.DpTableMdfFormInit;
import com.synesoft.fisp.app.dp.model.DpTableMdfForm.DpTableMdfFormMdf;
import com.synesoft.fisp.app.dp.model.DpTableQryForm.DpTableQryFormDel;

public class DpTable {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.TABLE_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    @NotEmpty(groups = {DpTableQryFormDel.class, DpTableDtlFormInit.class, DpTableMdfFormInit.class }, 
    		message = "{e.dp.table.0027}")
    private String tableId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.TABLE_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    @NotEmpty(groups = {DpTableAddFormAdd.class }, message = "{e.dp.table.0054}")
    @Size(groups = {DpTableAddFormAdd.class, DpTableMdfFormMdf.class }, min=0, max=32, message = "{e.dp.imp.0067}")
    private String tableName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.TABLE_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    @Size(groups = {DpTableAddFormAdd.class, DpTableMdfFormMdf.class }, min=0, max=128, message = "{e.dp.table.0083}")
    private String tableDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    @Size(groups = {DpTableAddFormAdd.class, DpTableMdfFormMdf.class }, min=0, max=128, message = "{e.dp.imp.0071}")
    private String comments;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.CREATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.CREATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.UPDATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String updateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.UPDATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String updateUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.TABLE_ID
     *
     * @return the value of DP_TABLE.TABLE_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.TABLE_ID
     *
     * @param tableId the value for DP_TABLE.TABLE_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.TABLE_NAME
     *
     * @return the value of DP_TABLE.TABLE_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.TABLE_NAME
     *
     * @param tableName the value for DP_TABLE.TABLE_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.TABLE_DESC
     *
     * @return the value of DP_TABLE.TABLE_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getTableDesc() {
        return tableDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.TABLE_DESC
     *
     * @param tableDesc the value for DP_TABLE.TABLE_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setTableDesc(String tableDesc) {
        this.tableDesc = tableDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.COMMENTS
     *
     * @return the value of DP_TABLE.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.COMMENTS
     *
     * @param comments the value for DP_TABLE.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.CREATE_TIME
     *
     * @return the value of DP_TABLE.CREATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.CREATE_TIME
     *
     * @param createTime the value for DP_TABLE.CREATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.CREATE_USER
     *
     * @return the value of DP_TABLE.CREATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.CREATE_USER
     *
     * @param createUser the value for DP_TABLE.CREATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.UPDATE_TIME
     *
     * @return the value of DP_TABLE.UPDATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.UPDATE_TIME
     *
     * @param updateTime the value for DP_TABLE.UPDATE_TIME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.UPDATE_USER
     *
     * @return the value of DP_TABLE.UPDATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.UPDATE_USER
     *
     * @param updateUser the value for DP_TABLE.UPDATE_USER
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.RSV1
     *
     * @return the value of DP_TABLE.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.RSV1
     *
     * @param rsv1 the value for DP_TABLE.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.RSV2
     *
     * @return the value of DP_TABLE.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.RSV2
     *
     * @param rsv2 the value for DP_TABLE.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.RSV3
     *
     * @return the value of DP_TABLE.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.RSV3
     *
     * @param rsv3 the value for DP_TABLE.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.RSV4
     *
     * @return the value of DP_TABLE.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.RSV4
     *
     * @param rsv4 the value for DP_TABLE.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE.RSV5
     *
     * @return the value of DP_TABLE.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE.RSV5
     *
     * @param rsv5 the value for DP_TABLE.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
}