package com.synesoft.fisp.domain.model;

public class RoleInf {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.ROLEID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String roleid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.ROLENAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rolename;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.ROLEDESC
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String roledesc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.MENULIST
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String menulist;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.CREATEORG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String createorg;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String creater;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String createtime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.LASTOPERATOR
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String lastoperator;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.LASTOPTTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String lastopttime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String checker;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String checktime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.OPTSTATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String optstatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.INFRUSEFLAG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String infruseflag;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv4;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ROLEINF.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv5;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.ROLEID
	 * @return  the value of ROLEINF.ROLEID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.ROLEID
	 * @param roleid  the value for ROLEINF.ROLEID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.ROLENAME
	 * @return  the value of ROLEINF.ROLENAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRolename() {
		return rolename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.ROLENAME
	 * @param rolename  the value for ROLEINF.ROLENAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.ROLEDESC
	 * @return  the value of ROLEINF.ROLEDESC
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRoledesc() {
		return roledesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.ROLEDESC
	 * @param roledesc  the value for ROLEINF.ROLEDESC
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRoledesc(String roledesc) {
		this.roledesc = roledesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.MENULIST
	 * @return  the value of ROLEINF.MENULIST
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getMenulist() {
		return menulist;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.MENULIST
	 * @param menulist  the value for ROLEINF.MENULIST
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setMenulist(String menulist) {
		this.menulist = menulist;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.CREATEORG
	 * @return  the value of ROLEINF.CREATEORG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreateorg() {
		return createorg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.CREATEORG
	 * @param createorg  the value for ROLEINF.CREATEORG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreateorg(String createorg) {
		this.createorg = createorg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.CREATER
	 * @return  the value of ROLEINF.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.CREATER
	 * @param creater  the value for ROLEINF.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreater(String creater) {
		this.creater = creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.CREATETIME
	 * @return  the value of ROLEINF.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.CREATETIME
	 * @param createtime  the value for ROLEINF.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.LASTOPERATOR
	 * @return  the value of ROLEINF.LASTOPERATOR
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getLastoperator() {
		return lastoperator;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.LASTOPERATOR
	 * @param lastoperator  the value for ROLEINF.LASTOPERATOR
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setLastoperator(String lastoperator) {
		this.lastoperator = lastoperator;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.LASTOPTTIME
	 * @return  the value of ROLEINF.LASTOPTTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getLastopttime() {
		return lastopttime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.LASTOPTTIME
	 * @param lastopttime  the value for ROLEINF.LASTOPTTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setLastopttime(String lastopttime) {
		this.lastopttime = lastopttime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.CHECKER
	 * @return  the value of ROLEINF.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getChecker() {
		return checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.CHECKER
	 * @param checker  the value for ROLEINF.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setChecker(String checker) {
		this.checker = checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.CHECKTIME
	 * @return  the value of ROLEINF.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getChecktime() {
		return checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.CHECKTIME
	 * @param checktime  the value for ROLEINF.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setChecktime(String checktime) {
		this.checktime = checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.OPTSTATUS
	 * @return  the value of ROLEINF.OPTSTATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getOptstatus() {
		return optstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.OPTSTATUS
	 * @param optstatus  the value for ROLEINF.OPTSTATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setOptstatus(String optstatus) {
		this.optstatus = optstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.INFRUSEFLAG
	 * @return  the value of ROLEINF.INFRUSEFLAG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getInfruseflag() {
		return infruseflag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.INFRUSEFLAG
	 * @param infruseflag  the value for ROLEINF.INFRUSEFLAG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setInfruseflag(String infruseflag) {
		this.infruseflag = infruseflag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.RSV1
	 * @return  the value of ROLEINF.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv1() {
		return rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.RSV1
	 * @param rsv1  the value for ROLEINF.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv1(String rsv1) {
		this.rsv1 = rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.RSV2
	 * @return  the value of ROLEINF.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv2() {
		return rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.RSV2
	 * @param rsv2  the value for ROLEINF.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv2(String rsv2) {
		this.rsv2 = rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.RSV3
	 * @return  the value of ROLEINF.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv3() {
		return rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.RSV3
	 * @param rsv3  the value for ROLEINF.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv3(String rsv3) {
		this.rsv3 = rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.RSV4
	 * @return  the value of ROLEINF.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv4() {
		return rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.RSV4
	 * @param rsv4  the value for ROLEINF.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv4(String rsv4) {
		this.rsv4 = rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ROLEINF.RSV5
	 * @return  the value of ROLEINF.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv5() {
		return rsv5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ROLEINF.RSV5
	 * @param rsv5  the value for ROLEINF.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv5(String rsv5) {
		this.rsv5 = rsv5;
	}
}