package com.synesoft.fisp.domain.model;

public class SysRoleFunc {
	private String funcId;
	private String roleId;
	private String optstatus;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_ROLE_FUNC.ADD_DATETIME
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    private String createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_ROLE_FUNC.ADD_USER_ID
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_ROLE_FUNC.UPD_DATETIME
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    private String updateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_ROLE_FUNC.UPD_USER_ID
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    private String updateUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_ROLE_FUNC.RSV1
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_ROLE_FUNC.RSV2
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_ROLE_FUNC.RSV3
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_ROLE_FUNC.RSV4
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_ROLE_FUNC.RSV5
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_ROLE_FUNC.RSV1
     *
     * @return the value of SYS_ROLE_FUNC.RSV1
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_ROLE_FUNC.RSV1
     *
     * @param rsv1 the value for SYS_ROLE_FUNC.RSV1
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_ROLE_FUNC.RSV2
     *
     * @return the value of SYS_ROLE_FUNC.RSV2
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_ROLE_FUNC.RSV2
     *
     * @param rsv2 the value for SYS_ROLE_FUNC.RSV2
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_ROLE_FUNC.RSV3
     *
     * @return the value of SYS_ROLE_FUNC.RSV3
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_ROLE_FUNC.RSV3
     *
     * @param rsv3 the value for SYS_ROLE_FUNC.RSV3
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_ROLE_FUNC.RSV4
     *
     * @return the value of SYS_ROLE_FUNC.RSV4
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_ROLE_FUNC.RSV4
     *
     * @param rsv4 the value for SYS_ROLE_FUNC.RSV4
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_ROLE_FUNC.RSV5
     *
     * @return the value of SYS_ROLE_FUNC.RSV5
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_ROLE_FUNC.RSV5
     *
     * @param rsv5 the value for SYS_ROLE_FUNC.RSV5
     *
     * @abatorgenerated Fri Nov 15 18:58:10 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }

	public String getFuncId() {
		return funcId;
	}

	public void setFuncId(String funcId) {
		this.funcId = funcId;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public String getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public String getOptstatus() {
		return optstatus;
	}

	public void setOptstatus(String optstatus) {
		this.optstatus = optstatus;
	}
}