package com.synesoft.fisp.domain.model;

public class SysUserRoleTmpKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE_TMP.ID
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String id;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE_TMP.ID
     *
     * @return the value of SYS_USER_ROLE_TMP.ID
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE_TMP.ID
     *
     * @param roleid the value for SYS_USER_ROLE_TMP.ID
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

}