package com.synesoft.fisp.domain.model;

public class SysUserRole extends SysUserRoleKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.USERNAME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String username;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.ROLENAME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String rolename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.OPTSTATUS
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String optstatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.CREATER
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String creater;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.CREATETIME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String createtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.LASTOPERATOR
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String lastoperator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.LASTOPTTIME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String lastopttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.CHECKER
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String checker;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.CHECKTIME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String checktime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.RSV1
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.RSV2
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.RSV3
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.RSV4
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USER_ROLE.RSV5
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.USERNAME
     *
     * @return the value of SYS_USER_ROLE.USERNAME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.USERNAME
     *
     * @param username the value for SYS_USER_ROLE.USERNAME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.ROLENAME
     *
     * @return the value of SYS_USER_ROLE.ROLENAME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.ROLENAME
     *
     * @param rolename the value for SYS_USER_ROLE.ROLENAME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.OPTSTATUS
     *
     * @return the value of SYS_USER_ROLE.OPTSTATUS
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getOptstatus() {
        return optstatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.OPTSTATUS
     *
     * @param optstatus the value for SYS_USER_ROLE.OPTSTATUS
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setOptstatus(String optstatus) {
        this.optstatus = optstatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.CREATER
     *
     * @return the value of SYS_USER_ROLE.CREATER
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.CREATER
     *
     * @param creater the value for SYS_USER_ROLE.CREATER
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.CREATETIME
     *
     * @return the value of SYS_USER_ROLE.CREATETIME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.CREATETIME
     *
     * @param createtime the value for SYS_USER_ROLE.CREATETIME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.LASTOPERATOR
     *
     * @return the value of SYS_USER_ROLE.LASTOPERATOR
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getLastoperator() {
        return lastoperator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.LASTOPERATOR
     *
     * @param lastoperator the value for SYS_USER_ROLE.LASTOPERATOR
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setLastoperator(String lastoperator) {
        this.lastoperator = lastoperator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.LASTOPTTIME
     *
     * @return the value of SYS_USER_ROLE.LASTOPTTIME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getLastopttime() {
        return lastopttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.LASTOPTTIME
     *
     * @param lastopttime the value for SYS_USER_ROLE.LASTOPTTIME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setLastopttime(String lastopttime) {
        this.lastopttime = lastopttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.CHECKER
     *
     * @return the value of SYS_USER_ROLE.CHECKER
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.CHECKER
     *
     * @param checker the value for SYS_USER_ROLE.CHECKER
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.CHECKTIME
     *
     * @return the value of SYS_USER_ROLE.CHECKTIME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.CHECKTIME
     *
     * @param checktime the value for SYS_USER_ROLE.CHECKTIME
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setChecktime(String checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.RSV1
     *
     * @return the value of SYS_USER_ROLE.RSV1
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.RSV1
     *
     * @param rsv1 the value for SYS_USER_ROLE.RSV1
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.RSV2
     *
     * @return the value of SYS_USER_ROLE.RSV2
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.RSV2
     *
     * @param rsv2 the value for SYS_USER_ROLE.RSV2
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.RSV3
     *
     * @return the value of SYS_USER_ROLE.RSV3
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.RSV3
     *
     * @param rsv3 the value for SYS_USER_ROLE.RSV3
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.RSV4
     *
     * @return the value of SYS_USER_ROLE.RSV4
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.RSV4
     *
     * @param rsv4 the value for SYS_USER_ROLE.RSV4
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USER_ROLE.RSV5
     *
     * @return the value of SYS_USER_ROLE.RSV5
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USER_ROLE.RSV5
     *
     * @param rsv5 the value for SYS_USER_ROLE.RSV5
     *
     * @abatorgenerated Fri Dec 20 11:00:07 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
}