package com.synesoft.fisp.domain.model;

public class TipsBaCInf implements IMemoryResource {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.RECKBANKNO
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String reckbankno;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.GENBANKNAME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String genbankname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.RECKONTYPE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String reckontype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.OFNODECODE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String ofnodecode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.ADDRESS
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.POSTALCODE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String postalcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.PEOPLENAME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String peoplename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.PEOPLEPHONE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String peoplephone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.PEOPLEMOBILE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String peoplemobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.EMAIL
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.OPERSIGN
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String opersign;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.EFFECTDATE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String effectdate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.UPDATEAREA
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String updatearea;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.CREATER
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String creater;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.CREATETIME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String createtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.LASTOPERATOR
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String lastoperator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.LASTOPTTIME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String lastopttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.CHECKER
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String checker;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.CHECKTIME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String checktime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.OPTSTATUS
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String optstatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.RSV1
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.RSV2
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.RSV3
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.RSV4
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TIPS_BACINF.RSV5
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.RECKBANKNO
     *
     * @return the value of TIPS_BACINF.RECKBANKNO
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getReckbankno() {
        return reckbankno;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.RECKBANKNO
     *
     * @param reckbankno the value for TIPS_BACINF.RECKBANKNO
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setReckbankno(String reckbankno) {
        this.reckbankno = reckbankno;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.GENBANKNAME
     *
     * @return the value of TIPS_BACINF.GENBANKNAME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getGenbankname() {
        return genbankname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.GENBANKNAME
     *
     * @param genbankname the value for TIPS_BACINF.GENBANKNAME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setGenbankname(String genbankname) {
        this.genbankname = genbankname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.RECKONTYPE
     *
     * @return the value of TIPS_BACINF.RECKONTYPE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getReckontype() {
        return reckontype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.RECKONTYPE
     *
     * @param reckontype the value for TIPS_BACINF.RECKONTYPE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setReckontype(String reckontype) {
        this.reckontype = reckontype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.OFNODECODE
     *
     * @return the value of TIPS_BACINF.OFNODECODE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getOfnodecode() {
        return ofnodecode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.OFNODECODE
     *
     * @param ofnodecode the value for TIPS_BACINF.OFNODECODE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setOfnodecode(String ofnodecode) {
        this.ofnodecode = ofnodecode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.ADDRESS
     *
     * @return the value of TIPS_BACINF.ADDRESS
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.ADDRESS
     *
     * @param address the value for TIPS_BACINF.ADDRESS
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.POSTALCODE
     *
     * @return the value of TIPS_BACINF.POSTALCODE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.POSTALCODE
     *
     * @param postalcode the value for TIPS_BACINF.POSTALCODE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.PEOPLENAME
     *
     * @return the value of TIPS_BACINF.PEOPLENAME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getPeoplename() {
        return peoplename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.PEOPLENAME
     *
     * @param peoplename the value for TIPS_BACINF.PEOPLENAME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setPeoplename(String peoplename) {
        this.peoplename = peoplename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.PEOPLEPHONE
     *
     * @return the value of TIPS_BACINF.PEOPLEPHONE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getPeoplephone() {
        return peoplephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.PEOPLEPHONE
     *
     * @param peoplephone the value for TIPS_BACINF.PEOPLEPHONE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setPeoplephone(String peoplephone) {
        this.peoplephone = peoplephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.PEOPLEMOBILE
     *
     * @return the value of TIPS_BACINF.PEOPLEMOBILE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getPeoplemobile() {
        return peoplemobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.PEOPLEMOBILE
     *
     * @param peoplemobile the value for TIPS_BACINF.PEOPLEMOBILE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setPeoplemobile(String peoplemobile) {
        this.peoplemobile = peoplemobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.EMAIL
     *
     * @return the value of TIPS_BACINF.EMAIL
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.EMAIL
     *
     * @param email the value for TIPS_BACINF.EMAIL
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.OPERSIGN
     *
     * @return the value of TIPS_BACINF.OPERSIGN
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getOpersign() {
        return opersign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.OPERSIGN
     *
     * @param opersign the value for TIPS_BACINF.OPERSIGN
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setOpersign(String opersign) {
        this.opersign = opersign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.EFFECTDATE
     *
     * @return the value of TIPS_BACINF.EFFECTDATE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.EFFECTDATE
     *
     * @param effectdate the value for TIPS_BACINF.EFFECTDATE
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setEffectdate(String effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.UPDATEAREA
     *
     * @return the value of TIPS_BACINF.UPDATEAREA
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getUpdatearea() {
        return updatearea;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.UPDATEAREA
     *
     * @param updatearea the value for TIPS_BACINF.UPDATEAREA
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setUpdatearea(String updatearea) {
        this.updatearea = updatearea;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.CREATER
     *
     * @return the value of TIPS_BACINF.CREATER
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.CREATER
     *
     * @param creater the value for TIPS_BACINF.CREATER
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.CREATETIME
     *
     * @return the value of TIPS_BACINF.CREATETIME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.CREATETIME
     *
     * @param createtime the value for TIPS_BACINF.CREATETIME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.LASTOPERATOR
     *
     * @return the value of TIPS_BACINF.LASTOPERATOR
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getLastoperator() {
        return lastoperator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.LASTOPERATOR
     *
     * @param lastoperator the value for TIPS_BACINF.LASTOPERATOR
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setLastoperator(String lastoperator) {
        this.lastoperator = lastoperator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.LASTOPTTIME
     *
     * @return the value of TIPS_BACINF.LASTOPTTIME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getLastopttime() {
        return lastopttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.LASTOPTTIME
     *
     * @param lastopttime the value for TIPS_BACINF.LASTOPTTIME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setLastopttime(String lastopttime) {
        this.lastopttime = lastopttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.CHECKER
     *
     * @return the value of TIPS_BACINF.CHECKER
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.CHECKER
     *
     * @param checker the value for TIPS_BACINF.CHECKER
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.CHECKTIME
     *
     * @return the value of TIPS_BACINF.CHECKTIME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.CHECKTIME
     *
     * @param checktime the value for TIPS_BACINF.CHECKTIME
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setChecktime(String checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.OPTSTATUS
     *
     * @return the value of TIPS_BACINF.OPTSTATUS
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getOptstatus() {
        return optstatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.OPTSTATUS
     *
     * @param optstatus the value for TIPS_BACINF.OPTSTATUS
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setOptstatus(String optstatus) {
        this.optstatus = optstatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.RSV1
     *
     * @return the value of TIPS_BACINF.RSV1
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.RSV1
     *
     * @param rsv1 the value for TIPS_BACINF.RSV1
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.RSV2
     *
     * @return the value of TIPS_BACINF.RSV2
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.RSV2
     *
     * @param rsv2 the value for TIPS_BACINF.RSV2
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.RSV3
     *
     * @return the value of TIPS_BACINF.RSV3
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.RSV3
     *
     * @param rsv3 the value for TIPS_BACINF.RSV3
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.RSV4
     *
     * @return the value of TIPS_BACINF.RSV4
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.RSV4
     *
     * @param rsv4 the value for TIPS_BACINF.RSV4
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TIPS_BACINF.RSV5
     *
     * @return the value of TIPS_BACINF.RSV5
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TIPS_BACINF.RSV5
     *
     * @param rsv5 the value for TIPS_BACINF.RSV5
     *
     * @abatorgenerated Thu Jul 11 18:04:39 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
    
	@Override
	public boolean searchByCode(String code) {
		if (code.equals(this.reckbankno.trim()))
			return true;
		else
			return false;
	}

	@Override
	public boolean searchByName(String name) {
		if (this.genbankname.contains(name))
			return true;
		else
			return false;
	}
}