package com.synesoft.fisp.domain.model;

public class UserOrgInfTmp {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.ID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.USERID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String userid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.ORGID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String orgid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.ORGNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String orgname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.OPTSTATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String optstatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.OPTTYPE
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String opttype;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String creater;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String createtime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String checker;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String checktime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv4;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERORGINFTMP.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv5;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.ID
	 * @return  the value of USERORGINFTMP.ID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.ID
	 * @param id  the value for USERORGINFTMP.ID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.USERID
	 * @return  the value of USERORGINFTMP.USERID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.USERID
	 * @param userid  the value for USERORGINFTMP.USERID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.ORGID
	 * @return  the value of USERORGINFTMP.ORGID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getOrgid() {
		return orgid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.ORGID
	 * @param orgid  the value for USERORGINFTMP.ORGID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.ORGNAME
	 * @return  the value of USERORGINFTMP.ORGNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getOrgname() {
		return orgname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.ORGNAME
	 * @param orgname  the value for USERORGINFTMP.ORGNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.OPTSTATUS
	 * @return  the value of USERORGINFTMP.OPTSTATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getOptstatus() {
		return optstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.OPTSTATUS
	 * @param optstatus  the value for USERORGINFTMP.OPTSTATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setOptstatus(String optstatus) {
		this.optstatus = optstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.OPTTYPE
	 * @return  the value of USERORGINFTMP.OPTTYPE
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getOpttype() {
		return opttype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.OPTTYPE
	 * @param opttype  the value for USERORGINFTMP.OPTTYPE
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setOpttype(String opttype) {
		this.opttype = opttype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.CREATER
	 * @return  the value of USERORGINFTMP.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.CREATER
	 * @param creater  the value for USERORGINFTMP.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreater(String creater) {
		this.creater = creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.CREATETIME
	 * @return  the value of USERORGINFTMP.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.CREATETIME
	 * @param createtime  the value for USERORGINFTMP.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.CHECKER
	 * @return  the value of USERORGINFTMP.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getChecker() {
		return checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.CHECKER
	 * @param checker  the value for USERORGINFTMP.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setChecker(String checker) {
		this.checker = checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.CHECKTIME
	 * @return  the value of USERORGINFTMP.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getChecktime() {
		return checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.CHECKTIME
	 * @param checktime  the value for USERORGINFTMP.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setChecktime(String checktime) {
		this.checktime = checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.RSV1
	 * @return  the value of USERORGINFTMP.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv1() {
		return rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.RSV1
	 * @param rsv1  the value for USERORGINFTMP.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv1(String rsv1) {
		this.rsv1 = rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.RSV2
	 * @return  the value of USERORGINFTMP.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv2() {
		return rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.RSV2
	 * @param rsv2  the value for USERORGINFTMP.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv2(String rsv2) {
		this.rsv2 = rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.RSV3
	 * @return  the value of USERORGINFTMP.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv3() {
		return rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.RSV3
	 * @param rsv3  the value for USERORGINFTMP.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv3(String rsv3) {
		this.rsv3 = rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.RSV4
	 * @return  the value of USERORGINFTMP.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv4() {
		return rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.RSV4
	 * @param rsv4  the value for USERORGINFTMP.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv4(String rsv4) {
		this.rsv4 = rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERORGINFTMP.RSV5
	 * @return  the value of USERORGINFTMP.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv5() {
		return rsv5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERORGINFTMP.RSV5
	 * @param rsv5  the value for USERORGINFTMP.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv5(String rsv5) {
		this.rsv5 = rsv5;
	}
}