package com.synesoft.pisa.domain.model;

public class XmlToTable {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column XML_TO_TABLE.XML_NO
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    private String xmlNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column XML_TO_TABLE.XML_TYPE
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    private String xmlType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column XML_TO_TABLE.NOTE_NAME
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    private String noteName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column XML_TO_TABLE.TABLE_OR_COLUMN
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    private String tableOrColumn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column XML_TO_TABLE.TYPE
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    private String type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column XML_TO_TABLE.PARENT_NO
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    private String parentNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column XML_TO_TABLE.SEQ_NO
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    private Short seqNo;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column XML_TO_TABLE.XML_NO
     *
     * @return the value of XML_TO_TABLE.XML_NO
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public String getXmlNo() {
        return xmlNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column XML_TO_TABLE.XML_NO
     *
     * @param xmlNo the value for XML_TO_TABLE.XML_NO
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public void setXmlNo(String xmlNo) {
        this.xmlNo = xmlNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column XML_TO_TABLE.XML_TYPE
     *
     * @return the value of XML_TO_TABLE.XML_TYPE
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public String getXmlType() {
        return xmlType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column XML_TO_TABLE.XML_TYPE
     *
     * @param xmlType the value for XML_TO_TABLE.XML_TYPE
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public void setXmlType(String xmlType) {
        this.xmlType = xmlType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column XML_TO_TABLE.NOTE_NAME
     *
     * @return the value of XML_TO_TABLE.NOTE_NAME
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public String getNoteName() {
        return noteName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column XML_TO_TABLE.NOTE_NAME
     *
     * @param noteName the value for XML_TO_TABLE.NOTE_NAME
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public void setNoteName(String noteName) {
        this.noteName = noteName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column XML_TO_TABLE.TABLE_OR_COLUMN
     *
     * @return the value of XML_TO_TABLE.TABLE_OR_COLUMN
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public String getTableOrColumn() {
        return tableOrColumn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column XML_TO_TABLE.TABLE_OR_COLUMN
     *
     * @param tableOrColumn the value for XML_TO_TABLE.TABLE_OR_COLUMN
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public void setTableOrColumn(String tableOrColumn) {
        this.tableOrColumn = tableOrColumn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column XML_TO_TABLE.TYPE
     *
     * @return the value of XML_TO_TABLE.TYPE
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column XML_TO_TABLE.TYPE
     *
     * @param type the value for XML_TO_TABLE.TYPE
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column XML_TO_TABLE.PARENT_NO
     *
     * @return the value of XML_TO_TABLE.PARENT_NO
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public String getParentNo() {
        return parentNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column XML_TO_TABLE.PARENT_NO
     *
     * @param parentNo the value for XML_TO_TABLE.PARENT_NO
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public void setParentNo(String parentNo) {
        this.parentNo = parentNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column XML_TO_TABLE.SEQ_NO
     *
     * @return the value of XML_TO_TABLE.SEQ_NO
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public Short getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column XML_TO_TABLE.SEQ_NO
     *
     * @param seqNo the value for XML_TO_TABLE.SEQ_NO
     *
     * @abatorgenerated Fri Dec 27 14:22:32 CST 2013
     */
    public void setSeqNo(Short seqNo) {
        this.seqNo = seqNo;
    }
}