package com.synesoft.fisp.domain.model;

public class DpExprTmp {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.UESR_ID
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.USER_SESSION
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String userSession;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.EXPRESS_NAME
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String expressName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.EXPRESS_VAL
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String expressVal;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.EXPRESS_RETURN
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String expressReturn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.RSV1
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.RSV2
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.RSV3
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.RSV4
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_TMP.RSV5
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.UESR_ID
     *
     * @return the value of DP_EXPR_TMP.UESR_ID
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    
    private String srcTable;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.USER_SESSION
     *
     * @return the value of DP_EXPR_TMP.USER_SESSION
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public String getUserSession() {
        return userSession;
    }

    public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_TMP.USER_SESSION
     *
     * @param userSession the value for DP_EXPR_TMP.USER_SESSION
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public void setUserSession(String userSession) {
        this.userSession = userSession;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.EXPRESS_NAME
     *
     * @return the value of DP_EXPR_TMP.EXPRESS_NAME
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public String getExpressName() {
        return expressName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_TMP.EXPRESS_NAME
     *
     * @param expressName the value for DP_EXPR_TMP.EXPRESS_NAME
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public void setExpressName(String expressName) {
        this.expressName = expressName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.EXPRESS_VAL
     *
     * @return the value of DP_EXPR_TMP.EXPRESS_VAL
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public String getExpressVal() {
        return expressVal;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_TMP.EXPRESS_VAL
     *
     * @param expressVal the value for DP_EXPR_TMP.EXPRESS_VAL
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public void setExpressVal(String expressVal) {
        this.expressVal = expressVal;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.EXPRESS_RETURN
     *
     * @return the value of DP_EXPR_TMP.EXPRESS_RETURN
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public String getExpressReturn() {
        return expressReturn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_TMP.EXPRESS_RETURN
     *
     * @param expressReturn the value for DP_EXPR_TMP.EXPRESS_RETURN
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public void setExpressReturn(String expressReturn) {
        this.expressReturn = expressReturn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.RSV1
     *
     * @return the value of DP_EXPR_TMP.RSV1
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_TMP.RSV1
     *
     * @param rsv1 the value for DP_EXPR_TMP.RSV1
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.RSV2
     *
     * @return the value of DP_EXPR_TMP.RSV2
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_TMP.RSV2
     *
     * @param rsv2 the value for DP_EXPR_TMP.RSV2
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.RSV3
     *
     * @return the value of DP_EXPR_TMP.RSV3
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_TMP.RSV3
     *
     * @param rsv3 the value for DP_EXPR_TMP.RSV3
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.RSV4
     *
     * @return the value of DP_EXPR_TMP.RSV4
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_TMP.RSV4
     *
     * @param rsv4 the value for DP_EXPR_TMP.RSV4
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_TMP.RSV5
     *
     * @return the value of DP_EXPR_TMP.RSV5
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_TMP.RSV5
     *
     * @param rsv5 the value for DP_EXPR_TMP.RSV5
     *
     * @abatorgenerated Fri Nov 15 15:34:30 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }

	public String getSrcTable() {
		return srcTable;
	}

	public void setSrcTable(String srcTable) {
		this.srcTable = srcTable;
	}
    
    
}