package com.synesoft.fisp.domain.model;

public class DpExprParaval {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.SEQ_NO
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String seqNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.DP_CFG_ID
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String dpCfgId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.MAP_TYPE
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String mapType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.BRANCH_ID
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String branchId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.PARAM_VALUE
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String paramValue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.PARAM_TYPE
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String paramType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.USE_FLAG
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String useFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.CREATE_TIME
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.CREATE_USER
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.RSV1
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.RSV2
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.RSV3
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.RSV4
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_EXPR_PARAVAL.RSV5
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.SEQ_NO
     *
     * @return the value of DP_EXPR_PARAVAL.SEQ_NO
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.SEQ_NO
     *
     * @param seqNo the value for DP_EXPR_PARAVAL.SEQ_NO
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.DP_CFG_ID
     *
     * @return the value of DP_EXPR_PARAVAL.DP_CFG_ID
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getDpCfgId() {
        return dpCfgId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.DP_CFG_ID
     *
     * @param dpCfgId the value for DP_EXPR_PARAVAL.DP_CFG_ID
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setDpCfgId(String dpCfgId) {
        this.dpCfgId = dpCfgId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.MAP_TYPE
     *
     * @return the value of DP_EXPR_PARAVAL.MAP_TYPE
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getMapType() {
        return mapType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.MAP_TYPE
     *
     * @param mapType the value for DP_EXPR_PARAVAL.MAP_TYPE
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setMapType(String mapType) {
        this.mapType = mapType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.BRANCH_ID
     *
     * @return the value of DP_EXPR_PARAVAL.BRANCH_ID
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.BRANCH_ID
     *
     * @param branchId the value for DP_EXPR_PARAVAL.BRANCH_ID
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.PARAM_VALUE
     *
     * @return the value of DP_EXPR_PARAVAL.PARAM_VALUE
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.PARAM_VALUE
     *
     * @param paramValue the value for DP_EXPR_PARAVAL.PARAM_VALUE
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.PARAM_TYPE
     *
     * @return the value of DP_EXPR_PARAVAL.PARAM_TYPE
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.PARAM_TYPE
     *
     * @param paramType the value for DP_EXPR_PARAVAL.PARAM_TYPE
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setParamType(String paramType) {
        this.paramType = paramType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.USE_FLAG
     *
     * @return the value of DP_EXPR_PARAVAL.USE_FLAG
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getUseFlag() {
        return useFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.USE_FLAG
     *
     * @param useFlag the value for DP_EXPR_PARAVAL.USE_FLAG
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.CREATE_TIME
     *
     * @return the value of DP_EXPR_PARAVAL.CREATE_TIME
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.CREATE_TIME
     *
     * @param createTime the value for DP_EXPR_PARAVAL.CREATE_TIME
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.CREATE_USER
     *
     * @return the value of DP_EXPR_PARAVAL.CREATE_USER
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.CREATE_USER
     *
     * @param createUser the value for DP_EXPR_PARAVAL.CREATE_USER
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.RSV1
     *
     * @return the value of DP_EXPR_PARAVAL.RSV1
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.RSV1
     *
     * @param rsv1 the value for DP_EXPR_PARAVAL.RSV1
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.RSV2
     *
     * @return the value of DP_EXPR_PARAVAL.RSV2
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.RSV2
     *
     * @param rsv2 the value for DP_EXPR_PARAVAL.RSV2
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.RSV3
     *
     * @return the value of DP_EXPR_PARAVAL.RSV3
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.RSV3
     *
     * @param rsv3 the value for DP_EXPR_PARAVAL.RSV3
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.RSV4
     *
     * @return the value of DP_EXPR_PARAVAL.RSV4
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.RSV4
     *
     * @param rsv4 the value for DP_EXPR_PARAVAL.RSV4
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_EXPR_PARAVAL.RSV5
     *
     * @return the value of DP_EXPR_PARAVAL.RSV5
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_EXPR_PARAVAL.RSV5
     *
     * @param rsv5 the value for DP_EXPR_PARAVAL.RSV5
     *
     * @abatorgenerated Wed Dec 04 10:56:18 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
}