package com.synesoft.fisp.domain.model;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.synesoft.fisp.app.dp.model.DpFileAddForm.DpFileAddFormAdd;
import com.synesoft.fisp.app.dp.model.DpFileMdfForm.DpFileMdfFormMdf;

public class DpFileDtl {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.FIELD_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String fieldId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.FILE_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String fileId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.FIELD_SEQ_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private Short fieldSeqNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.FIELD_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String fieldName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.FIELD_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    @NotEmpty(groups = {DpFileAddFormAdd.class, DpFileMdfFormMdf.class }, message = "{e.dp.file.0086}")
    @Size(groups = {DpFileAddFormAdd.class, DpFileMdfFormMdf.class }, min=0, max=128, message = "{e.dp.file.0088}")
    private String fieldDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.FIELD_LEN
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private Short fieldLen;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.CUT_FLAG
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String cutFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String comments;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_FILE_DTL.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.FIELD_ID
     *
     * @return the value of DP_FILE_DTL.FIELD_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.FIELD_ID
     *
     * @param fieldId the value for DP_FILE_DTL.FIELD_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setFieldId(String fieldId) {
        this.fieldId = fieldId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.FILE_ID
     *
     * @return the value of DP_FILE_DTL.FILE_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.FILE_ID
     *
     * @param fileId the value for DP_FILE_DTL.FILE_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.FIELD_SEQ_NO
     *
     * @return the value of DP_FILE_DTL.FIELD_SEQ_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public Short getFieldSeqNo() {
        return fieldSeqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.FIELD_SEQ_NO
     *
     * @param fieldSeqNo the value for DP_FILE_DTL.FIELD_SEQ_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setFieldSeqNo(Short fieldSeqNo) {
        this.fieldSeqNo = fieldSeqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.FIELD_NAME
     *
     * @return the value of DP_FILE_DTL.FIELD_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.FIELD_NAME
     *
     * @param fieldName the value for DP_FILE_DTL.FIELD_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.FIELD_DESC
     *
     * @return the value of DP_FILE_DTL.FIELD_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getFieldDesc() {
        return fieldDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.FIELD_DESC
     *
     * @param fieldDesc the value for DP_FILE_DTL.FIELD_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setFieldDesc(String fieldDesc) {
        this.fieldDesc = fieldDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.FIELD_LEN
     *
     * @return the value of DP_FILE_DTL.FIELD_LEN
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public Short getFieldLen() {
        return fieldLen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.FIELD_LEN
     *
     * @param fieldLen the value for DP_FILE_DTL.FIELD_LEN
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setFieldLen(Short fieldLen) {
        this.fieldLen = fieldLen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.CUT_FLAG
     *
     * @return the value of DP_FILE_DTL.CUT_FLAG
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getCutFlag() {
        return cutFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.CUT_FLAG
     *
     * @param cutFlag the value for DP_FILE_DTL.CUT_FLAG
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setCutFlag(String cutFlag) {
        this.cutFlag = cutFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.COMMENTS
     *
     * @return the value of DP_FILE_DTL.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.COMMENTS
     *
     * @param comments the value for DP_FILE_DTL.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.RSV1
     *
     * @return the value of DP_FILE_DTL.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.RSV1
     *
     * @param rsv1 the value for DP_FILE_DTL.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.RSV2
     *
     * @return the value of DP_FILE_DTL.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.RSV2
     *
     * @param rsv2 the value for DP_FILE_DTL.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.RSV3
     *
     * @return the value of DP_FILE_DTL.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.RSV3
     *
     * @param rsv3 the value for DP_FILE_DTL.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.RSV4
     *
     * @return the value of DP_FILE_DTL.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.RSV4
     *
     * @param rsv4 the value for DP_FILE_DTL.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_FILE_DTL.RSV5
     *
     * @return the value of DP_FILE_DTL.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_FILE_DTL.RSV5
     *
     * @param rsv5 the value for DP_FILE_DTL.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
}