package com.synesoft.fisp.domain.model;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.synesoft.fisp.app.dp.model.DpTableAddForm.DpTableAddFormAdd;
import com.synesoft.fisp.app.dp.model.DpTableDtlDtlForm.DpTableDtlDtlFormInit;
import com.synesoft.fisp.app.dp.model.DpTableMdfForm.DpTableMdfFormMdf;

public class DpTableDtl {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.COL_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
     @NotEmpty(groups = {DpTableDtlDtlFormInit.class }, message = "{e.dp.table.0055}")
    private String colId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.TABLE_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String tableId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.COL_SEQ_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private Short colSeqNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.COL_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String colName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.COL_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    @NotEmpty(groups = {DpTableAddFormAdd.class, DpTableMdfFormMdf.class }, message = "{e.dp.table.0087}")
    @Size(groups = {DpTableAddFormAdd.class, DpTableMdfFormMdf.class }, min=0, max=128, message = "{e.dp.table.0089}")
    private String colDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.COL_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String colType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.COL_LEN
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String colLen;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String comments;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DP_TABLE_DTL.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.COL_ID
     *
     * @return the value of DP_TABLE_DTL.COL_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getColId() {
        return colId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.COL_ID
     *
     * @param colId the value for DP_TABLE_DTL.COL_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setColId(String colId) {
        this.colId = colId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.TABLE_ID
     *
     * @return the value of DP_TABLE_DTL.TABLE_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.TABLE_ID
     *
     * @param tableId the value for DP_TABLE_DTL.TABLE_ID
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.COL_SEQ_NO
     *
     * @return the value of DP_TABLE_DTL.COL_SEQ_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public Short getColSeqNo() {
        return colSeqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.COL_SEQ_NO
     *
     * @param colSeqNo the value for DP_TABLE_DTL.COL_SEQ_NO
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setColSeqNo(Short colSeqNo) {
        this.colSeqNo = colSeqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.COL_NAME
     *
     * @return the value of DP_TABLE_DTL.COL_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getColName() {
        return colName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.COL_NAME
     *
     * @param colName the value for DP_TABLE_DTL.COL_NAME
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setColName(String colName) {
        this.colName = colName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.COL_DESC
     *
     * @return the value of DP_TABLE_DTL.COL_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getColDesc() {
        return colDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.COL_DESC
     *
     * @param colDesc the value for DP_TABLE_DTL.COL_DESC
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setColDesc(String colDesc) {
        this.colDesc = colDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.COL_TYPE
     *
     * @return the value of DP_TABLE_DTL.COL_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getColType() {
        return colType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.COL_TYPE
     *
     * @param colType the value for DP_TABLE_DTL.COL_TYPE
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setColType(String colType) {
        this.colType = colType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.COL_LEN
     *
     * @return the value of DP_TABLE_DTL.COL_LEN
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getColLen() {
        return colLen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.COL_LEN
     *
     * @param colLen the value for DP_TABLE_DTL.COL_LEN
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setColLen(String colLen) {
        this.colLen = colLen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.COMMENTS
     *
     * @return the value of DP_TABLE_DTL.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.COMMENTS
     *
     * @param comments the value for DP_TABLE_DTL.COMMENTS
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.RSV1
     *
     * @return the value of DP_TABLE_DTL.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.RSV1
     *
     * @param rsv1 the value for DP_TABLE_DTL.RSV1
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.RSV2
     *
     * @return the value of DP_TABLE_DTL.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.RSV2
     *
     * @param rsv2 the value for DP_TABLE_DTL.RSV2
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.RSV3
     *
     * @return the value of DP_TABLE_DTL.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.RSV3
     *
     * @param rsv3 the value for DP_TABLE_DTL.RSV3
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.RSV4
     *
     * @return the value of DP_TABLE_DTL.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.RSV4
     *
     * @param rsv4 the value for DP_TABLE_DTL.RSV4
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DP_TABLE_DTL.RSV5
     *
     * @return the value of DP_TABLE_DTL.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DP_TABLE_DTL.RSV5
     *
     * @param rsv5 the value for DP_TABLE_DTL.RSV5
     *
     * @abatorgenerated Tue Nov 12 10:03:54 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
}