package com.synesoft.fisp.domain.model;

public class OrgRoleInf extends OrgRoleInfKey {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.ORGNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String orgname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String creater;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String createtime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String checker;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String checktime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv4;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ORGROLEINF.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv5;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.ORGNAME
	 * @return  the value of ORGROLEINF.ORGNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getOrgname() {
		return orgname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.ORGNAME
	 * @param orgname  the value for ORGROLEINF.ORGNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.CREATER
	 * @return  the value of ORGROLEINF.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.CREATER
	 * @param creater  the value for ORGROLEINF.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreater(String creater) {
		this.creater = creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.CREATETIME
	 * @return  the value of ORGROLEINF.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.CREATETIME
	 * @param createtime  the value for ORGROLEINF.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.CHECKER
	 * @return  the value of ORGROLEINF.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getChecker() {
		return checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.CHECKER
	 * @param checker  the value for ORGROLEINF.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setChecker(String checker) {
		this.checker = checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.CHECKTIME
	 * @return  the value of ORGROLEINF.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getChecktime() {
		return checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.CHECKTIME
	 * @param checktime  the value for ORGROLEINF.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setChecktime(String checktime) {
		this.checktime = checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.RSV1
	 * @return  the value of ORGROLEINF.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv1() {
		return rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.RSV1
	 * @param rsv1  the value for ORGROLEINF.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv1(String rsv1) {
		this.rsv1 = rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.RSV2
	 * @return  the value of ORGROLEINF.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv2() {
		return rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.RSV2
	 * @param rsv2  the value for ORGROLEINF.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv2(String rsv2) {
		this.rsv2 = rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.RSV3
	 * @return  the value of ORGROLEINF.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv3() {
		return rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.RSV3
	 * @param rsv3  the value for ORGROLEINF.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv3(String rsv3) {
		this.rsv3 = rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.RSV4
	 * @return  the value of ORGROLEINF.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv4() {
		return rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.RSV4
	 * @param rsv4  the value for ORGROLEINF.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv4(String rsv4) {
		this.rsv4 = rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ORGROLEINF.RSV5
	 * @return  the value of ORGROLEINF.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv5() {
		return rsv5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ORGROLEINF.RSV5
	 * @param rsv5  the value for ORGROLEINF.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv5(String rsv5) {
		this.rsv5 = rsv5;
	}
}