package com.synesoft.fisp.domain.model;

import java.math.BigDecimal;

public class ReportDataDetail {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.REPORT_DETAIL_ID
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private String reportDetailId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.REPORT_ID
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private String reportId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.MSG_TYPE
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private String msgType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.SUM_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private BigDecimal sumCnt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.INPUT_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private Integer inputCnt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.AUTH_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private Integer authCnt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.ERROR_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private Integer errorCnt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.SUM_AMOUNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private BigDecimal sumAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.ERROR_STATUS
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private String errorStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.RSV1
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.RSV2
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.RSV3
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.RSV4
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column REPORT_DATA_DETAIL.RSV5
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.REPORT_DETAIL_ID
     *
     * @return the value of REPORT_DATA_DETAIL.REPORT_DETAIL_ID
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public String getReportDetailId() {
        return reportDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.REPORT_DETAIL_ID
     *
     * @param reportDetailId the value for REPORT_DATA_DETAIL.REPORT_DETAIL_ID
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setReportDetailId(String reportDetailId) {
        this.reportDetailId = reportDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.REPORT_ID
     *
     * @return the value of REPORT_DATA_DETAIL.REPORT_ID
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.REPORT_ID
     *
     * @param reportId the value for REPORT_DATA_DETAIL.REPORT_ID
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.MSG_TYPE
     *
     * @return the value of REPORT_DATA_DETAIL.MSG_TYPE
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.MSG_TYPE
     *
     * @param msgType the value for REPORT_DATA_DETAIL.MSG_TYPE
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.SUM_CNT
     *
     * @return the value of REPORT_DATA_DETAIL.SUM_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public BigDecimal getSumCnt() {
        return sumCnt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.SUM_CNT
     *
     * @param sumCnt the value for REPORT_DATA_DETAIL.SUM_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setSumCnt(BigDecimal sumCnt) {
        this.sumCnt = sumCnt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.INPUT_CNT
     *
     * @return the value of REPORT_DATA_DETAIL.INPUT_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public Integer getInputCnt() {
        return inputCnt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.INPUT_CNT
     *
     * @param inputCnt the value for REPORT_DATA_DETAIL.INPUT_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setInputCnt(Integer inputCnt) {
        this.inputCnt = inputCnt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.AUTH_CNT
     *
     * @return the value of REPORT_DATA_DETAIL.AUTH_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public Integer getAuthCnt() {
        return authCnt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.AUTH_CNT
     *
     * @param authCnt the value for REPORT_DATA_DETAIL.AUTH_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setAuthCnt(Integer authCnt) {
        this.authCnt = authCnt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.ERROR_CNT
     *
     * @return the value of REPORT_DATA_DETAIL.ERROR_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public Integer getErrorCnt() {
        return errorCnt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.ERROR_CNT
     *
     * @param errorCnt the value for REPORT_DATA_DETAIL.ERROR_CNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setErrorCnt(Integer errorCnt) {
        this.errorCnt = errorCnt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.SUM_AMOUNT
     *
     * @return the value of REPORT_DATA_DETAIL.SUM_AMOUNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public BigDecimal getSumAmount() {
        return sumAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.SUM_AMOUNT
     *
     * @param sumAmount the value for REPORT_DATA_DETAIL.SUM_AMOUNT
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setSumAmount(BigDecimal sumAmount) {
        this.sumAmount = sumAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.ERROR_STATUS
     *
     * @return the value of REPORT_DATA_DETAIL.ERROR_STATUS
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public String getErrorStatus() {
        return errorStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.ERROR_STATUS
     *
     * @param errorStatus the value for REPORT_DATA_DETAIL.ERROR_STATUS
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setErrorStatus(String errorStatus) {
        this.errorStatus = errorStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.RSV1
     *
     * @return the value of REPORT_DATA_DETAIL.RSV1
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.RSV1
     *
     * @param rsv1 the value for REPORT_DATA_DETAIL.RSV1
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.RSV2
     *
     * @return the value of REPORT_DATA_DETAIL.RSV2
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.RSV2
     *
     * @param rsv2 the value for REPORT_DATA_DETAIL.RSV2
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.RSV3
     *
     * @return the value of REPORT_DATA_DETAIL.RSV3
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.RSV3
     *
     * @param rsv3 the value for REPORT_DATA_DETAIL.RSV3
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.RSV4
     *
     * @return the value of REPORT_DATA_DETAIL.RSV4
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.RSV4
     *
     * @param rsv4 the value for REPORT_DATA_DETAIL.RSV4
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column REPORT_DATA_DETAIL.RSV5
     *
     * @return the value of REPORT_DATA_DETAIL.RSV5
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column REPORT_DATA_DETAIL.RSV5
     *
     * @param rsv5 the value for REPORT_DATA_DETAIL.RSV5
     *
     * @abatorgenerated Thu Sep 26 17:02:29 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }
}