package com.synesoft.fisp.domain.model;

public class SysControlDept {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.ID
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.CONTROL_ID
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String controlId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.PAGE_ID
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String pageId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.CONTROL_DEPT
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String controlDept;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.CONTROL_NAME
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String controlName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.CHECK_FLAG
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String checkFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.CREATE_TIME
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.CREATE_USER
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String createUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.UPDATE_TIME
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String updateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_CONTROL_DEPT.UPDATE_USER
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    private String updateUser;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.ID
     *
     * @return the value of SYS_CONTROL_DEPT.ID
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.ID
     *
     * @param id the value for SYS_CONTROL_DEPT.ID
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.CONTROL_ID
     *
     * @return the value of SYS_CONTROL_DEPT.CONTROL_ID
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getControlId() {
        return controlId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.CONTROL_ID
     *
     * @param controlId the value for SYS_CONTROL_DEPT.CONTROL_ID
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setControlId(String controlId) {
        this.controlId = controlId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.PAGE_ID
     *
     * @return the value of SYS_CONTROL_DEPT.PAGE_ID
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getPageId() {
        return pageId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.PAGE_ID
     *
     * @param pageId the value for SYS_CONTROL_DEPT.PAGE_ID
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setPageId(String pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.CONTROL_DEPT
     *
     * @return the value of SYS_CONTROL_DEPT.CONTROL_DEPT
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getControlDept() {
        return controlDept;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.CONTROL_DEPT
     *
     * @param controlDept the value for SYS_CONTROL_DEPT.CONTROL_DEPT
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setControlDept(String controlDept) {
        this.controlDept = controlDept;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.CONTROL_NAME
     *
     * @return the value of SYS_CONTROL_DEPT.CONTROL_NAME
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getControlName() {
        return controlName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.CONTROL_NAME
     *
     * @param controlName the value for SYS_CONTROL_DEPT.CONTROL_NAME
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setControlName(String controlName) {
        this.controlName = controlName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.CHECK_FLAG
     *
     * @return the value of SYS_CONTROL_DEPT.CHECK_FLAG
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getCheckFlag() {
        return checkFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.CHECK_FLAG
     *
     * @param checkFlag the value for SYS_CONTROL_DEPT.CHECK_FLAG
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setCheckFlag(String checkFlag) {
        this.checkFlag = checkFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.CREATE_TIME
     *
     * @return the value of SYS_CONTROL_DEPT.CREATE_TIME
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.CREATE_TIME
     *
     * @param createTime the value for SYS_CONTROL_DEPT.CREATE_TIME
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.CREATE_USER
     *
     * @return the value of SYS_CONTROL_DEPT.CREATE_USER
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.CREATE_USER
     *
     * @param createUser the value for SYS_CONTROL_DEPT.CREATE_USER
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.UPDATE_TIME
     *
     * @return the value of SYS_CONTROL_DEPT.UPDATE_TIME
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.UPDATE_TIME
     *
     * @param updateTime the value for SYS_CONTROL_DEPT.UPDATE_TIME
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_CONTROL_DEPT.UPDATE_USER
     *
     * @return the value of SYS_CONTROL_DEPT.UPDATE_USER
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_CONTROL_DEPT.UPDATE_USER
     *
     * @param updateUser the value for SYS_CONTROL_DEPT.UPDATE_USER
     *
     * @abatorgenerated Tue Feb 18 15:05:33 CST 2014
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
}