package com.synesoft.fisp.domain.model;

public class UserInfTmp {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.ID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.USERID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String userid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.USERNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String username;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.CREATEORG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String createorg;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.LOGINORG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String loginorg;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.STATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String userstatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.OPTSTATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String optstatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.OPTTYPE
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String opttype;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.AUTHAMT
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private Long authamt;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.STAFFID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String staffid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.STAFFNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String staffname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.DEPARTMENT
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String department;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.GENDER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String gender;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.MAIL
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String mail;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.TELNO
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String telno;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String creater;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String createtime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String checker;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String checktime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv4;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERINFTMP.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	private String rsv5;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.ID
	 * @return  the value of USERINFTMP.ID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.ID
	 * @param id  the value for USERINFTMP.ID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.USERID
	 * @return  the value of USERINFTMP.USERID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.USERID
	 * @param userid  the value for USERINFTMP.USERID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.USERNAME
	 * @return  the value of USERINFTMP.USERNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.USERNAME
	 * @param username  the value for USERINFTMP.USERNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.CREATEORG
	 * @return  the value of USERINFTMP.CREATEORG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreateorg() {
		return createorg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.CREATEORG
	 * @param createorg  the value for USERINFTMP.CREATEORG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreateorg(String createorg) {
		this.createorg = createorg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.LOGINORG
	 * @return  the value of USERINFTMP.LOGINORG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getLoginorg() {
		return loginorg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.LOGINORG
	 * @param loginorg  the value for USERINFTMP.LOGINORG
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setLoginorg(String loginorg) {
		this.loginorg = loginorg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.STATUS
	 * @return  the value of USERINFTMP.STATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getUserstatus() {
		return userstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.STATUS
	 * @param status  the value for USERINFTMP.STATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setUserstatus(String userstatus) {
		this.userstatus = userstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.OPTSTATUS
	 * @return  the value of USERINFTMP.OPTSTATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getOptstatus() {
		return optstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.OPTSTATUS
	 * @param optstatus  the value for USERINFTMP.OPTSTATUS
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setOptstatus(String optstatus) {
		this.optstatus = optstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.OPTTYPE
	 * @return  the value of USERINFTMP.OPTTYPE
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getOpttype() {
		return opttype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.OPTTYPE
	 * @param opttype  the value for USERINFTMP.OPTTYPE
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setOpttype(String opttype) {
		this.opttype = opttype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.AUTHAMT
	 * @return  the value of USERINFTMP.AUTHAMT
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public Long getAuthamt() {
		return authamt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.AUTHAMT
	 * @param authamt  the value for USERINFTMP.AUTHAMT
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setAuthamt(Long authamt) {
		this.authamt = authamt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.STAFFID
	 * @return  the value of USERINFTMP.STAFFID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getStaffid() {
		return staffid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.STAFFID
	 * @param staffid  the value for USERINFTMP.STAFFID
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setStaffid(String staffid) {
		this.staffid = staffid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.STAFFNAME
	 * @return  the value of USERINFTMP.STAFFNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getStaffname() {
		return staffname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.STAFFNAME
	 * @param staffname  the value for USERINFTMP.STAFFNAME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setStaffname(String staffname) {
		this.staffname = staffname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.DEPARTMENT
	 * @return  the value of USERINFTMP.DEPARTMENT
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.DEPARTMENT
	 * @param department  the value for USERINFTMP.DEPARTMENT
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.GENDER
	 * @return  the value of USERINFTMP.GENDER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.GENDER
	 * @param gender  the value for USERINFTMP.GENDER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.MAIL
	 * @return  the value of USERINFTMP.MAIL
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.MAIL
	 * @param mail  the value for USERINFTMP.MAIL
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.TELNO
	 * @return  the value of USERINFTMP.TELNO
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getTelno() {
		return telno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.TELNO
	 * @param telno  the value for USERINFTMP.TELNO
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setTelno(String telno) {
		this.telno = telno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.CREATER
	 * @return  the value of USERINFTMP.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.CREATER
	 * @param creater  the value for USERINFTMP.CREATER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreater(String creater) {
		this.creater = creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.CREATETIME
	 * @return  the value of USERINFTMP.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.CREATETIME
	 * @param createtime  the value for USERINFTMP.CREATETIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.CHECKER
	 * @return  the value of USERINFTMP.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getChecker() {
		return checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.CHECKER
	 * @param checker  the value for USERINFTMP.CHECKER
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setChecker(String checker) {
		this.checker = checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.CHECKTIME
	 * @return  the value of USERINFTMP.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getChecktime() {
		return checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.CHECKTIME
	 * @param checktime  the value for USERINFTMP.CHECKTIME
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setChecktime(String checktime) {
		this.checktime = checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.RSV1
	 * @return  the value of USERINFTMP.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv1() {
		return rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.RSV1
	 * @param rsv1  the value for USERINFTMP.RSV1
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv1(String rsv1) {
		this.rsv1 = rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.RSV2
	 * @return  the value of USERINFTMP.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv2() {
		return rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.RSV2
	 * @param rsv2  the value for USERINFTMP.RSV2
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv2(String rsv2) {
		this.rsv2 = rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.RSV3
	 * @return  the value of USERINFTMP.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv3() {
		return rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.RSV3
	 * @param rsv3  the value for USERINFTMP.RSV3
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv3(String rsv3) {
		this.rsv3 = rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.RSV4
	 * @return  the value of USERINFTMP.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv4() {
		return rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.RSV4
	 * @param rsv4  the value for USERINFTMP.RSV4
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv4(String rsv4) {
		this.rsv4 = rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERINFTMP.RSV5
	 * @return  the value of USERINFTMP.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public String getRsv5() {
		return rsv5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERINFTMP.RSV5
	 * @param rsv5  the value for USERINFTMP.RSV5
	 * @abatorgenerated  Tue Jul 16 10:43:31 CST 2013
	 */
	public void setRsv5(String rsv5) {
		this.rsv5 = rsv5;
	}
}