package com.synesoft.pisa.domain.model;

import java.math.BigDecimal;

public class BizDraftDrawList {
    /**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.SEQ_NO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String seqNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.INST_ID
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String instId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.VOC_NO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String vocNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAYER_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payerName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAYER_ACTNO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payerActno;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAYER_BANK_CODE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payerBankCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAYER_BANK_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payerBankName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAYEE_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payeeName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAYEE_ACTNO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payeeActno;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_CODE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payeeBankCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payeeBankName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.AGRMT_NO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String agrmtNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.ACPT_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String acptName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.ACPT_ACTNO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String acptActno;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.ACPT_BANK_CODE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String acptBankCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.ACPT_BANK_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String acptBankName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.START_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String startDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.END_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String endDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.DRAFT_AMT
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private BigDecimal draftAmt;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.DRAFT_TYPE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String draftType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.DISC_TYPE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String discType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.DISC_TERM
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String discTerm;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAYEE_BIZ_TYPE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payeeBizType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.ADV_AMT
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private BigDecimal advAmt;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.WOFF_AMT
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private BigDecimal woffAmt;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.DRAFT_STS
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String draftSts;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.RCV_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String rcvDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.SELL_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String sellDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.DISC_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String discDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.RED_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String redDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.COLL_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String collDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.PAY_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String payDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.ADV_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String advDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.WOFF_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String woffDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.OPT_STS
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String optSts;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.INPUT_USER
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String inputUser;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.INPUT_TIME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String inputTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.CHECK_USER
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String checkUser;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.CHECK_TIME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String checkTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.COMMENTS
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String comments;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.RSV1
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String rsv1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.RSV2
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String rsv2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.RSV3
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String rsv3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.RSV4
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String rsv4;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column BIZ_DRAFT_DRAW_LIST.RSV5
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	private String rsv5;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.SEQ_NO
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.SEQ_NO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getSeqNo() {
		return seqNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.SEQ_NO
	 * @param seqNo  the value for BIZ_DRAFT_DRAW_LIST.SEQ_NO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setSeqNo(String seqNo) {
		this.seqNo = seqNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.INST_ID
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.INST_ID
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getInstId() {
		return instId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.INST_ID
	 * @param instId  the value for BIZ_DRAFT_DRAW_LIST.INST_ID
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setInstId(String instId) {
		this.instId = instId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.VOC_NO
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.VOC_NO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getVocNo() {
		return vocNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.VOC_NO
	 * @param vocNo  the value for BIZ_DRAFT_DRAW_LIST.VOC_NO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setVocNo(String vocNo) {
		this.vocNo = vocNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAYER_NAME
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAYER_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayerName() {
		return payerName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAYER_NAME
	 * @param payerName  the value for BIZ_DRAFT_DRAW_LIST.PAYER_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAYER_ACTNO
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAYER_ACTNO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayerActno() {
		return payerActno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAYER_ACTNO
	 * @param payerActno  the value for BIZ_DRAFT_DRAW_LIST.PAYER_ACTNO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayerActno(String payerActno) {
		this.payerActno = payerActno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAYER_BANK_CODE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAYER_BANK_CODE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayerBankCode() {
		return payerBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAYER_BANK_CODE
	 * @param payerBankCode  the value for BIZ_DRAFT_DRAW_LIST.PAYER_BANK_CODE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayerBankCode(String payerBankCode) {
		this.payerBankCode = payerBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAYER_BANK_NAME
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAYER_BANK_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayerBankName() {
		return payerBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAYER_BANK_NAME
	 * @param payerBankName  the value for BIZ_DRAFT_DRAW_LIST.PAYER_BANK_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayerBankName(String payerBankName) {
		this.payerBankName = payerBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_NAME
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAYEE_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayeeName() {
		return payeeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_NAME
	 * @param payeeName  the value for BIZ_DRAFT_DRAW_LIST.PAYEE_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_ACTNO
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAYEE_ACTNO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayeeActno() {
		return payeeActno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_ACTNO
	 * @param payeeActno  the value for BIZ_DRAFT_DRAW_LIST.PAYEE_ACTNO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayeeActno(String payeeActno) {
		this.payeeActno = payeeActno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_CODE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_CODE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayeeBankCode() {
		return payeeBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_CODE
	 * @param payeeBankCode  the value for BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_CODE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayeeBankCode(String payeeBankCode) {
		this.payeeBankCode = payeeBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_NAME
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayeeBankName() {
		return payeeBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_NAME
	 * @param payeeBankName  the value for BIZ_DRAFT_DRAW_LIST.PAYEE_BANK_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayeeBankName(String payeeBankName) {
		this.payeeBankName = payeeBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.AGRMT_NO
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.AGRMT_NO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getAgrmtNo() {
		return agrmtNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.AGRMT_NO
	 * @param agrmtNo  the value for BIZ_DRAFT_DRAW_LIST.AGRMT_NO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setAgrmtNo(String agrmtNo) {
		this.agrmtNo = agrmtNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.ACPT_NAME
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.ACPT_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getAcptName() {
		return acptName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.ACPT_NAME
	 * @param acptName  the value for BIZ_DRAFT_DRAW_LIST.ACPT_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setAcptName(String acptName) {
		this.acptName = acptName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.ACPT_ACTNO
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.ACPT_ACTNO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getAcptActno() {
		return acptActno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.ACPT_ACTNO
	 * @param acptActno  the value for BIZ_DRAFT_DRAW_LIST.ACPT_ACTNO
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setAcptActno(String acptActno) {
		this.acptActno = acptActno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.ACPT_BANK_CODE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.ACPT_BANK_CODE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getAcptBankCode() {
		return acptBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.ACPT_BANK_CODE
	 * @param acptBankCode  the value for BIZ_DRAFT_DRAW_LIST.ACPT_BANK_CODE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setAcptBankCode(String acptBankCode) {
		this.acptBankCode = acptBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.ACPT_BANK_NAME
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.ACPT_BANK_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getAcptBankName() {
		return acptBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.ACPT_BANK_NAME
	 * @param acptBankName  the value for BIZ_DRAFT_DRAW_LIST.ACPT_BANK_NAME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setAcptBankName(String acptBankName) {
		this.acptBankName = acptBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.START_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.START_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.START_DATE
	 * @param startDate  the value for BIZ_DRAFT_DRAW_LIST.START_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.END_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.END_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.END_DATE
	 * @param endDate  the value for BIZ_DRAFT_DRAW_LIST.END_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.DRAFT_AMT
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.DRAFT_AMT
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public BigDecimal getDraftAmt() {
		return draftAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.DRAFT_AMT
	 * @param draftAmt  the value for BIZ_DRAFT_DRAW_LIST.DRAFT_AMT
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setDraftAmt(BigDecimal draftAmt) {
		this.draftAmt = draftAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.DRAFT_TYPE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.DRAFT_TYPE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getDraftType() {
		return draftType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.DRAFT_TYPE
	 * @param draftType  the value for BIZ_DRAFT_DRAW_LIST.DRAFT_TYPE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setDraftType(String draftType) {
		this.draftType = draftType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.DISC_TYPE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.DISC_TYPE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getDiscType() {
		return discType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.DISC_TYPE
	 * @param discType  the value for BIZ_DRAFT_DRAW_LIST.DISC_TYPE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setDiscType(String discType) {
		this.discType = discType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.DISC_TERM
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.DISC_TERM
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getDiscTerm() {
		return discTerm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.DISC_TERM
	 * @param discTerm  the value for BIZ_DRAFT_DRAW_LIST.DISC_TERM
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setDiscTerm(String discTerm) {
		this.discTerm = discTerm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_BIZ_TYPE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAYEE_BIZ_TYPE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayeeBizType() {
		return payeeBizType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAYEE_BIZ_TYPE
	 * @param payeeBizType  the value for BIZ_DRAFT_DRAW_LIST.PAYEE_BIZ_TYPE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayeeBizType(String payeeBizType) {
		this.payeeBizType = payeeBizType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.ADV_AMT
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.ADV_AMT
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public BigDecimal getAdvAmt() {
		return advAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.ADV_AMT
	 * @param advAmt  the value for BIZ_DRAFT_DRAW_LIST.ADV_AMT
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setAdvAmt(BigDecimal advAmt) {
		this.advAmt = advAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.WOFF_AMT
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.WOFF_AMT
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public BigDecimal getWoffAmt() {
		return woffAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.WOFF_AMT
	 * @param woffAmt  the value for BIZ_DRAFT_DRAW_LIST.WOFF_AMT
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setWoffAmt(BigDecimal woffAmt) {
		this.woffAmt = woffAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.DRAFT_STS
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.DRAFT_STS
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getDraftSts() {
		return draftSts;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.DRAFT_STS
	 * @param draftSts  the value for BIZ_DRAFT_DRAW_LIST.DRAFT_STS
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setDraftSts(String draftSts) {
		this.draftSts = draftSts;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.RCV_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.RCV_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getRcvDate() {
		return rcvDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.RCV_DATE
	 * @param rcvDate  the value for BIZ_DRAFT_DRAW_LIST.RCV_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setRcvDate(String rcvDate) {
		this.rcvDate = rcvDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.SELL_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.SELL_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getSellDate() {
		return sellDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.SELL_DATE
	 * @param sellDate  the value for BIZ_DRAFT_DRAW_LIST.SELL_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setSellDate(String sellDate) {
		this.sellDate = sellDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.DISC_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.DISC_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getDiscDate() {
		return discDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.DISC_DATE
	 * @param discDate  the value for BIZ_DRAFT_DRAW_LIST.DISC_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setDiscDate(String discDate) {
		this.discDate = discDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.RED_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.RED_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getRedDate() {
		return redDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.RED_DATE
	 * @param redDate  the value for BIZ_DRAFT_DRAW_LIST.RED_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setRedDate(String redDate) {
		this.redDate = redDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.COLL_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.COLL_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getCollDate() {
		return collDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.COLL_DATE
	 * @param collDate  the value for BIZ_DRAFT_DRAW_LIST.COLL_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setCollDate(String collDate) {
		this.collDate = collDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.PAY_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.PAY_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getPayDate() {
		return payDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.PAY_DATE
	 * @param payDate  the value for BIZ_DRAFT_DRAW_LIST.PAY_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setPayDate(String payDate) {
		this.payDate = payDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.ADV_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.ADV_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getAdvDate() {
		return advDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.ADV_DATE
	 * @param advDate  the value for BIZ_DRAFT_DRAW_LIST.ADV_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setAdvDate(String advDate) {
		this.advDate = advDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.WOFF_DATE
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.WOFF_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getWoffDate() {
		return woffDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.WOFF_DATE
	 * @param woffDate  the value for BIZ_DRAFT_DRAW_LIST.WOFF_DATE
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setWoffDate(String woffDate) {
		this.woffDate = woffDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.OPT_STS
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.OPT_STS
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getOptSts() {
		return optSts;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.OPT_STS
	 * @param optSts  the value for BIZ_DRAFT_DRAW_LIST.OPT_STS
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setOptSts(String optSts) {
		this.optSts = optSts;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.INPUT_USER
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.INPUT_USER
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getInputUser() {
		return inputUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.INPUT_USER
	 * @param inputUser  the value for BIZ_DRAFT_DRAW_LIST.INPUT_USER
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setInputUser(String inputUser) {
		this.inputUser = inputUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.INPUT_TIME
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.INPUT_TIME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getInputTime() {
		return inputTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.INPUT_TIME
	 * @param inputTime  the value for BIZ_DRAFT_DRAW_LIST.INPUT_TIME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setInputTime(String inputTime) {
		this.inputTime = inputTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.CHECK_USER
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.CHECK_USER
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getCheckUser() {
		return checkUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.CHECK_USER
	 * @param checkUser  the value for BIZ_DRAFT_DRAW_LIST.CHECK_USER
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setCheckUser(String checkUser) {
		this.checkUser = checkUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.CHECK_TIME
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.CHECK_TIME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getCheckTime() {
		return checkTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.CHECK_TIME
	 * @param checkTime  the value for BIZ_DRAFT_DRAW_LIST.CHECK_TIME
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.COMMENTS
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.COMMENTS
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.COMMENTS
	 * @param comments  the value for BIZ_DRAFT_DRAW_LIST.COMMENTS
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.RSV1
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.RSV1
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getRsv1() {
		return rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.RSV1
	 * @param rsv1  the value for BIZ_DRAFT_DRAW_LIST.RSV1
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setRsv1(String rsv1) {
		this.rsv1 = rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.RSV2
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.RSV2
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getRsv2() {
		return rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.RSV2
	 * @param rsv2  the value for BIZ_DRAFT_DRAW_LIST.RSV2
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setRsv2(String rsv2) {
		this.rsv2 = rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.RSV3
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.RSV3
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getRsv3() {
		return rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.RSV3
	 * @param rsv3  the value for BIZ_DRAFT_DRAW_LIST.RSV3
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setRsv3(String rsv3) {
		this.rsv3 = rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.RSV4
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.RSV4
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getRsv4() {
		return rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.RSV4
	 * @param rsv4  the value for BIZ_DRAFT_DRAW_LIST.RSV4
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setRsv4(String rsv4) {
		this.rsv4 = rsv4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column BIZ_DRAFT_DRAW_LIST.RSV5
	 * @return  the value of BIZ_DRAFT_DRAW_LIST.RSV5
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public String getRsv5() {
		return rsv5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column BIZ_DRAFT_DRAW_LIST.RSV5
	 * @param rsv5  the value for BIZ_DRAFT_DRAW_LIST.RSV5
	 * @abatorgenerated  Mon Nov 25 11:10:32 CST 2013
	 */
	public void setRsv5(String rsv5) {
		this.rsv5 = rsv5;
	}

	private BigDecimal minDraftAmt;
    private BigDecimal maxDraftAmt;

    /**
	 * @return the minDraftAmt
	 */
	public BigDecimal getMinDraftAmt() {
		return minDraftAmt;
	}

	/**
	 * @param minDraftAmt the minDraftAmt to set
	 */
	public void setMinDraftAmt(BigDecimal minDraftAmt) {
		this.minDraftAmt = minDraftAmt;
	}

	/**
	 * @return the maxDraftAmt
	 */
	public BigDecimal getMaxDraftAmt() {
		return maxDraftAmt;
	}

	/**
	 * @param maxDraftAmt the maxDraftAmt to set
	 */
	public void setMaxDraftAmt(BigDecimal maxDraftAmt) {
		this.maxDraftAmt = maxDraftAmt;
	}
}