package com.synesoft.pisa.domain.model;

public class ExpSheetFormula {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.FORMULA_ID
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String formulaId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.SHEET_NO
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String sheetNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.FORMULA_NAME
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String formulaName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.FORMULA_DESC
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String formulaDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.ITEM_NO
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String itemNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.DIM_NO
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String dimNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.DIM_NAME
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String dimName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.ITEM_NAME
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String itemName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.FORMULA
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String formula;
    
    private String formulaArea;
    
    
    /**
	 * @return the formulaArea
	 */
	public String getFormulaArea() {
		return formulaArea;
	}

	/**
	 * @param formulaArea the formulaArea to set
	 */
	public void setFormulaArea(String formulaArea) {
		this.formulaArea = formulaArea;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.CREATER
     *
     * @abatorgenerated Fri Dec 20 14:37:02 CST 2013
     */
    private String creater;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.CREATE_TIME
     *
     * @abatorgenerated Fri Dec 20 14:37:02 CST 2013
     */
    private String createTime;

    private String updater;
    
    private String updateTime;
    
    
    /**
	 * @return the updater
	 */
	public String getUpdater() {
		return updater;
	}

	/**
	 * @param updater the updater to set
	 */
	public void setUpdater(String updater) {
		this.updater = updater;
	}

	/**
	 * @return the updateTime
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.RSV1
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.RSV2
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.RSV3
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String rsv3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.RSV4
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String rsv4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EXP_SHEET_FORMULA.RSV5
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    private String rsv5;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.FORMULA_ID
     *
     * @return the value of EXP_SHEET_FORMULA.FORMULA_ID
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getFormulaId() {
        return formulaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.FORMULA_ID
     *
     * @param formulaId the value for EXP_SHEET_FORMULA.FORMULA_ID
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setFormulaId(String formulaId) {
        this.formulaId = formulaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.SHEET_NO
     *
     * @return the value of EXP_SHEET_FORMULA.SHEET_NO
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getSheetNo() {
        return sheetNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.SHEET_NO
     *
     * @param sheetNo the value for EXP_SHEET_FORMULA.SHEET_NO
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setSheetNo(String sheetNo) {
        this.sheetNo = sheetNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.FORMULA_NAME
     *
     * @return the value of EXP_SHEET_FORMULA.FORMULA_NAME
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getFormulaName() {
        return formulaName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.FORMULA_NAME
     *
     * @param formulaName the value for EXP_SHEET_FORMULA.FORMULA_NAME
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setFormulaName(String formulaName) {
        this.formulaName = formulaName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.FORMULA_DESC
     *
     * @return the value of EXP_SHEET_FORMULA.FORMULA_DESC
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getFormulaDesc() {
        return formulaDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.FORMULA_DESC
     *
     * @param formulaDesc the value for EXP_SHEET_FORMULA.FORMULA_DESC
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setFormulaDesc(String formulaDesc) {
        this.formulaDesc = formulaDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.ITEM_NO
     *
     * @return the value of EXP_SHEET_FORMULA.ITEM_NO
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.ITEM_NO
     *
     * @param itemNo the value for EXP_SHEET_FORMULA.ITEM_NO
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.DIM_NO
     *
     * @return the value of EXP_SHEET_FORMULA.DIM_NO
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getDimNo() {
        return dimNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.DIM_NO
     *
     * @param dimNo the value for EXP_SHEET_FORMULA.DIM_NO
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setDimNo(String dimNo) {
        this.dimNo = dimNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.DIM_NAME
     *
     * @return the value of EXP_SHEET_FORMULA.DIM_NAME
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getDimName() {
        return dimName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.DIM_NAME
     *
     * @param dimName the value for EXP_SHEET_FORMULA.DIM_NAME
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setDimName(String dimName) {
        this.dimName = dimName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.ITEM_NAME
     *
     * @return the value of EXP_SHEET_FORMULA.ITEM_NAME
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.ITEM_NAME
     *
     * @param itemName the value for EXP_SHEET_FORMULA.ITEM_NAME
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.FORMULA
     *
     * @return the value of EXP_SHEET_FORMULA.FORMULA
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getFormula() {
        return formula;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.FORMULA
     *
     * @param formula the value for EXP_SHEET_FORMULA.FORMULA
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setFormula(String formula) {
        this.formula = formula;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.RSV1
     *
     * @return the value of EXP_SHEET_FORMULA.RSV1
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.RSV1
     *
     * @param rsv1 the value for EXP_SHEET_FORMULA.RSV1
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.RSV2
     *
     * @return the value of EXP_SHEET_FORMULA.RSV2
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.RSV2
     *
     * @param rsv2 the value for EXP_SHEET_FORMULA.RSV2
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.RSV3
     *
     * @return the value of EXP_SHEET_FORMULA.RSV3
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.RSV3
     *
     * @param rsv3 the value for EXP_SHEET_FORMULA.RSV3
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.RSV4
     *
     * @return the value of EXP_SHEET_FORMULA.RSV4
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getRsv4() {
        return rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.RSV4
     *
     * @param rsv4 the value for EXP_SHEET_FORMULA.RSV4
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setRsv4(String rsv4) {
        this.rsv4 = rsv4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EXP_SHEET_FORMULA.RSV5
     *
     * @return the value of EXP_SHEET_FORMULA.RSV5
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public String getRsv5() {
        return rsv5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EXP_SHEET_FORMULA.RSV5
     *
     * @param rsv5 the value for EXP_SHEET_FORMULA.RSV5
     *
     * @abatorgenerated Fri Dec 20 13:24:15 CST 2013
     */
    public void setRsv5(String rsv5) {
        this.rsv5 = rsv5;
    }

	/**
	 * @return the creater
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * @param creater the creater to set
	 */
	public void setCreater(String creater) {
		this.creater = creater;
	}

	/**
	 * @return the createTime
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
}