package com.synesoft.ftzmis.domain.model;

import java.math.BigDecimal;

public class FtzActMstrTmp extends FtzActMstrTmpKey {
	private String submitDate;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.BRANCH_ID
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String branchId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.SEQ_NO
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String seqNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.CURRENCY
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String currency;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.DEPT_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String deptType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.BALANCE_CODE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String balanceCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.ACC_ORG_CODE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String accOrgCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.ACCOUNT_NAME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String accountName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.ACC_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String accType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.DEPOSIT_RATE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private BigDecimal depositRate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.CUSTOM_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String customType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.DOCUMENT_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String documentType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.DOCUMENT_NO
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String documentNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.ACC_STATUS
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String accStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.LAST_BALANCE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private BigDecimal lastBalance;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.DEBIT_COUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private Integer debitCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.DEBIT_AMOUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private BigDecimal debitAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.CREDIT_COUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private Integer creditCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.CREDIT_AMOUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private BigDecimal creditAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.BALANCE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private BigDecimal balance;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.CHECK_STATUS
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String checkStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.CHECK_DATETIME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String checkDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.MAK_USER_ID
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String makUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.MAK_DATETIME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String makDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.CHK_USER_ID
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String chkUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.CHK_DATETIME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String chkDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.CHK_ADD_WORD
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String chkAddWord;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.OP_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String opType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.RSV1
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.RSV2
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_ACT_MSTR_TMP.RSV3
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    private String rsv3;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.BRANCH_ID
     *
     * @return the value of FTZ_ACT_MSTR_TMP.BRANCH_ID
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getBranchId() {
        return branchId;
    }
    
    

    public String getSubmitDate() {
		return submitDate;
	}



	public void setSubmitDate(String submitDate) {
		this.submitDate = submitDate;
	}



	/**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.BRANCH_ID
     *
     * @param branchId the value for FTZ_ACT_MSTR_TMP.BRANCH_ID
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.SEQ_NO
     *
     * @return the value of FTZ_ACT_MSTR_TMP.SEQ_NO
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.SEQ_NO
     *
     * @param seqNo the value for FTZ_ACT_MSTR_TMP.SEQ_NO
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.CURRENCY
     *
     * @return the value of FTZ_ACT_MSTR_TMP.CURRENCY
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.CURRENCY
     *
     * @param currency the value for FTZ_ACT_MSTR_TMP.CURRENCY
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.DEPT_TYPE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.DEPT_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getDeptType() {
        return deptType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.DEPT_TYPE
     *
     * @param deptType the value for FTZ_ACT_MSTR_TMP.DEPT_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setDeptType(String deptType) {
        this.deptType = deptType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.BALANCE_CODE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.BALANCE_CODE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getBalanceCode() {
        return balanceCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.BALANCE_CODE
     *
     * @param balanceCode the value for FTZ_ACT_MSTR_TMP.BALANCE_CODE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setBalanceCode(String balanceCode) {
        this.balanceCode = balanceCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.ACC_ORG_CODE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.ACC_ORG_CODE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getAccOrgCode() {
        return accOrgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.ACC_ORG_CODE
     *
     * @param accOrgCode the value for FTZ_ACT_MSTR_TMP.ACC_ORG_CODE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setAccOrgCode(String accOrgCode) {
        this.accOrgCode = accOrgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.ACCOUNT_NAME
     *
     * @return the value of FTZ_ACT_MSTR_TMP.ACCOUNT_NAME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.ACCOUNT_NAME
     *
     * @param accountName the value for FTZ_ACT_MSTR_TMP.ACCOUNT_NAME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.ACC_TYPE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.ACC_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getAccType() {
        return accType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.ACC_TYPE
     *
     * @param accType the value for FTZ_ACT_MSTR_TMP.ACC_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setAccType(String accType) {
        this.accType = accType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.DEPOSIT_RATE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.DEPOSIT_RATE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public BigDecimal getDepositRate() {
        return depositRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.DEPOSIT_RATE
     *
     * @param depositRate the value for FTZ_ACT_MSTR_TMP.DEPOSIT_RATE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setDepositRate(BigDecimal depositRate) {
        this.depositRate = depositRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.CUSTOM_TYPE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.CUSTOM_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getCustomType() {
        return customType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.CUSTOM_TYPE
     *
     * @param customType the value for FTZ_ACT_MSTR_TMP.CUSTOM_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setCustomType(String customType) {
        this.customType = customType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.DOCUMENT_TYPE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.DOCUMENT_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.DOCUMENT_TYPE
     *
     * @param documentType the value for FTZ_ACT_MSTR_TMP.DOCUMENT_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.DOCUMENT_NO
     *
     * @return the value of FTZ_ACT_MSTR_TMP.DOCUMENT_NO
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getDocumentNo() {
        return documentNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.DOCUMENT_NO
     *
     * @param documentNo the value for FTZ_ACT_MSTR_TMP.DOCUMENT_NO
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.ACC_STATUS
     *
     * @return the value of FTZ_ACT_MSTR_TMP.ACC_STATUS
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getAccStatus() {
        return accStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.ACC_STATUS
     *
     * @param accStatus the value for FTZ_ACT_MSTR_TMP.ACC_STATUS
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setAccStatus(String accStatus) {
        this.accStatus = accStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.LAST_BALANCE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.LAST_BALANCE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public BigDecimal getLastBalance() {
        return lastBalance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.LAST_BALANCE
     *
     * @param lastBalance the value for FTZ_ACT_MSTR_TMP.LAST_BALANCE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setLastBalance(BigDecimal lastBalance) {
        this.lastBalance = lastBalance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.DEBIT_COUNT
     *
     * @return the value of FTZ_ACT_MSTR_TMP.DEBIT_COUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public Integer getDebitCount() {
        return debitCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.DEBIT_COUNT
     *
     * @param debitCount the value for FTZ_ACT_MSTR_TMP.DEBIT_COUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setDebitCount(Integer debitCount) {
        this.debitCount = debitCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.DEBIT_AMOUNT
     *
     * @return the value of FTZ_ACT_MSTR_TMP.DEBIT_AMOUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public BigDecimal getDebitAmount() {
        return debitAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.DEBIT_AMOUNT
     *
     * @param debitAmount the value for FTZ_ACT_MSTR_TMP.DEBIT_AMOUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setDebitAmount(BigDecimal debitAmount) {
        this.debitAmount = debitAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.CREDIT_COUNT
     *
     * @return the value of FTZ_ACT_MSTR_TMP.CREDIT_COUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public Integer getCreditCount() {
        return creditCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.CREDIT_COUNT
     *
     * @param creditCount the value for FTZ_ACT_MSTR_TMP.CREDIT_COUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setCreditCount(Integer creditCount) {
        this.creditCount = creditCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.CREDIT_AMOUNT
     *
     * @return the value of FTZ_ACT_MSTR_TMP.CREDIT_AMOUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public BigDecimal getCreditAmount() {
        return creditAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.CREDIT_AMOUNT
     *
     * @param creditAmount the value for FTZ_ACT_MSTR_TMP.CREDIT_AMOUNT
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setCreditAmount(BigDecimal creditAmount) {
        this.creditAmount = creditAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.BALANCE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.BALANCE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.BALANCE
     *
     * @param balance the value for FTZ_ACT_MSTR_TMP.BALANCE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.CHECK_STATUS
     *
     * @return the value of FTZ_ACT_MSTR_TMP.CHECK_STATUS
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.CHECK_STATUS
     *
     * @param checkStatus the value for FTZ_ACT_MSTR_TMP.CHECK_STATUS
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.CHECK_DATETIME
     *
     * @return the value of FTZ_ACT_MSTR_TMP.CHECK_DATETIME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getCheckDatetime() {
        return checkDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.CHECK_DATETIME
     *
     * @param checkDatetime the value for FTZ_ACT_MSTR_TMP.CHECK_DATETIME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setCheckDatetime(String checkDatetime) {
        this.checkDatetime = checkDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.MAK_USER_ID
     *
     * @return the value of FTZ_ACT_MSTR_TMP.MAK_USER_ID
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getMakUserId() {
        return makUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.MAK_USER_ID
     *
     * @param makUserId the value for FTZ_ACT_MSTR_TMP.MAK_USER_ID
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setMakUserId(String makUserId) {
        this.makUserId = makUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.MAK_DATETIME
     *
     * @return the value of FTZ_ACT_MSTR_TMP.MAK_DATETIME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getMakDatetime() {
        return makDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.MAK_DATETIME
     *
     * @param makDatetime the value for FTZ_ACT_MSTR_TMP.MAK_DATETIME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setMakDatetime(String makDatetime) {
        this.makDatetime = makDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.CHK_USER_ID
     *
     * @return the value of FTZ_ACT_MSTR_TMP.CHK_USER_ID
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getChkUserId() {
        return chkUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.CHK_USER_ID
     *
     * @param chkUserId the value for FTZ_ACT_MSTR_TMP.CHK_USER_ID
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setChkUserId(String chkUserId) {
        this.chkUserId = chkUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.CHK_DATETIME
     *
     * @return the value of FTZ_ACT_MSTR_TMP.CHK_DATETIME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getChkDatetime() {
        return chkDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.CHK_DATETIME
     *
     * @param chkDatetime the value for FTZ_ACT_MSTR_TMP.CHK_DATETIME
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setChkDatetime(String chkDatetime) {
        this.chkDatetime = chkDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.CHK_ADD_WORD
     *
     * @return the value of FTZ_ACT_MSTR_TMP.CHK_ADD_WORD
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getChkAddWord() {
        return chkAddWord;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.CHK_ADD_WORD
     *
     * @param chkAddWord the value for FTZ_ACT_MSTR_TMP.CHK_ADD_WORD
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setChkAddWord(String chkAddWord) {
        this.chkAddWord = chkAddWord;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.OP_TYPE
     *
     * @return the value of FTZ_ACT_MSTR_TMP.OP_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.OP_TYPE
     *
     * @param opType the value for FTZ_ACT_MSTR_TMP.OP_TYPE
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setOpType(String opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.RSV1
     *
     * @return the value of FTZ_ACT_MSTR_TMP.RSV1
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.RSV1
     *
     * @param rsv1 the value for FTZ_ACT_MSTR_TMP.RSV1
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.RSV2
     *
     * @return the value of FTZ_ACT_MSTR_TMP.RSV2
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.RSV2
     *
     * @param rsv2 the value for FTZ_ACT_MSTR_TMP.RSV2
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_ACT_MSTR_TMP.RSV3
     *
     * @return the value of FTZ_ACT_MSTR_TMP.RSV3
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_ACT_MSTR_TMP.RSV3
     *
     * @param rsv3 the value for FTZ_ACT_MSTR_TMP.RSV3
     *
     * @abatorgenerated Tue Jan 28 11:28:14 CST 2014
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }
}