package com.synesoft.ftzmis.domain.model;

import java.math.BigDecimal;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

import com.synesoft.fisp.app.common.utils.MessagesUtil;
import com.synesoft.ftzmis.app.common.constants.CommonConst;
import com.synesoft.ftzmis.app.model.FTZ210101Form.FTZ210101FormAddDtlDtl;
import com.synesoft.ftzmis.app.model.FTZ210102Form.FTZ210102FormAddDtlDtl;
import com.synesoft.ftzmis.app.model.FTZ210103Form.FTZ210103FormAddDtlDtl;
import com.synesoft.ftzmis.app.model.FTZ210104Form.FTZ210104FormAddDtlDtl;
import com.synesoft.ftzmis.app.model.FTZ210105Form.FTZ210105FormAddDtlDtl;
import com.synesoft.ftzmis.app.model.FTZ210106Form.FTZ210106FormAddDtlDtl;
import com.synesoft.ftzmis.app.model.FTZ210112Form.FTZ210112FormAddDtlDtl;
import com.synesoft.ftzmis.app.model.FTZ210201Form.FTZ210201FormAddDtlDtl;

public class FtzInTxnDtl extends FtzInTxnDtlKey {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.CD_FLAG
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotEmpty(groups = { FTZ210101FormAddDtlDtl.class,
			FTZ210102FormAddDtlDtl.class, FTZ210103FormAddDtlDtl.class,
			FTZ210104FormAddDtlDtl.class, FTZ210105FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0013}")
	private String cdFlag;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.TRAN_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotEmpty(groups = { FTZ210101FormAddDtlDtl.class,
			FTZ210102FormAddDtlDtl.class, FTZ210103FormAddDtlDtl.class,
			FTZ210104FormAddDtlDtl.class, FTZ210106FormAddDtlDtl.class,
			FTZ210105FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0014}")
	private String tranDate;

	private String accOrgCode;

	public String getAccOrgCode() {
		return accOrgCode;
	}

	public void setAccOrgCode(String accOrgCode) {
		this.accOrgCode = accOrgCode;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.ORG_TRAN_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotEmpty(groups = { FTZ210106FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0015}")
	private String orgTranDate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.AMOUNT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotNull(groups = { FTZ210101FormAddDtlDtl.class,
			FTZ210112FormAddDtlDtl.class, FTZ210102FormAddDtlDtl.class,
			FTZ210103FormAddDtlDtl.class, FTZ210104FormAddDtlDtl.class,
			FTZ210105FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0015}")
	private BigDecimal amount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.OPP_ACCOUNT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String oppAccount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.OPP_NAME
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotEmpty(groups = { FTZ210106FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0015}")
	private String oppName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.OPP_BANK_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String oppBankCode;

	private String oppBankName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.COUNTRY_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotEmpty(groups = { FTZ210101FormAddDtlDtl.class,
			FTZ210102FormAddDtlDtl.class, FTZ210103FormAddDtlDtl.class,
			FTZ210105FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0016}")
	private String countryCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.DISITRICT_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String disitrictCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.TRAN_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotEmpty(groups = { FTZ210101FormAddDtlDtl.class,
			FTZ210102FormAddDtlDtl.class, FTZ210103FormAddDtlDtl.class,
			FTZ210104FormAddDtlDtl.class, FTZ210106FormAddDtlDtl.class,
			FTZ210106FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0017}")
	private String tranType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.TERM_LENGTH
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotNull(groups = { FTZ210102FormAddDtlDtl.class,
			FTZ210201FormAddDtlDtl.class, FTZ210106FormAddDtlDtl.class,
			FTZ210105FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0018}")
	private Short termLength;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.TERM_UNIT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotEmpty(groups = { FTZ210102FormAddDtlDtl.class,
			FTZ210106FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0019}")
	private String termUnit;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.VALUE_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotEmpty(groups = { FTZ210102FormAddDtlDtl.class,
			FTZ210103FormAddDtlDtl.class, FTZ210105FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0020}")
	private String valueDate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.EXPIRE_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotEmpty(groups = { FTZ210102FormAddDtlDtl.class,
			FTZ210103FormAddDtlDtl.class, FTZ210106FormAddDtlDtl.class,
			FTZ210105FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0021}")
	private String expireDate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.INTEREST_RATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotNull(groups = { FTZ210102FormAddDtlDtl.class,
			FTZ210106FormAddDtlDtl.class, FTZ210103FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0022}")
	private BigDecimal interestRate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.ISSUE_AMOUNT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	@NotNull(groups = { FTZ210102FormAddDtlDtl.class }, message = "{e.ftzmis.210101.0023}")
	private BigDecimal issueAmount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.ASSETS_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String assetsType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.ASSETS_VALUE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private BigDecimal assetsValue;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.EXCHANGE_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String exchangeType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.BUY_CURR
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String buyCurr;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.BUY_AMT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private BigDecimal buyAmt;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.BUY_RATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private BigDecimal buyRate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.SELL_CURR
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String sellCurr;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.SELL_AMT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private BigDecimal sellAmt;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.SELL_RATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private BigDecimal sellRate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.DOCUMENT_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String documentType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.DOCUMENT_NO
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String documentNo;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.LOAN_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String loanType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.OVERDUE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String overdue;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.SECURITIES_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String securitiesType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.SECURITIES_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String securitiesCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.OPP_CUS_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String oppCusType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.CHK_STATUS
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String chkStatus;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.RSV1
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String rsv1;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.RSV2
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String rsv2;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_TXN_DTL.RSV3
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	private String rsv3;

	private String makUserId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_MSG_CTL.MAK_DATETIME
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:39 CST 2013
	 */
	private String makDatetime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_MSG_CTL.CHK_USER_ID
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:39 CST 2013
	 */
	private String chkUserId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column FTZ_IN_MSG_CTL.CHK_DATETIME
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:39 CST 2013
	 */
	private String chkDatetime;

	private String chkAddWord;

	private String dtlSendStatus;
	
	private int cdCount;
	
	private BigDecimal cdSum;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.CD_FLAG
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.CD_FLAG
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getCdFlag() {
		return cdFlag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.CD_FLAG
	 * 
	 * @param cdFlag
	 *            the value for FTZ_IN_TXN_DTL.CD_FLAG
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setCdFlag(String cdFlag) {
		this.cdFlag = cdFlag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.TRAN_DATE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.TRAN_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getTranDate() {
		return tranDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.TRAN_DATE
	 * 
	 * @param tranDate
	 *            the value for FTZ_IN_TXN_DTL.TRAN_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setTranDate(String tranDate) {
		this.tranDate = tranDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.ORG_TRAN_DATE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.ORG_TRAN_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getOrgTranDate() {
		return orgTranDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.ORG_TRAN_DATE
	 * 
	 * @param orgTranDate
	 *            the value for FTZ_IN_TXN_DTL.ORG_TRAN_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setOrgTranDate(String orgTranDate) {
		this.orgTranDate = orgTranDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.AMOUNT
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.AMOUNT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.AMOUNT
	 * 
	 * @param amount
	 *            the value for FTZ_IN_TXN_DTL.AMOUNT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.OPP_ACCOUNT
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.OPP_ACCOUNT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getOppAccount() {
		return oppAccount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.OPP_ACCOUNT
	 * 
	 * @param oppAccount
	 *            the value for FTZ_IN_TXN_DTL.OPP_ACCOUNT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setOppAccount(String oppAccount) {
		this.oppAccount = oppAccount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.OPP_NAME
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.OPP_NAME
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getOppName() {
		return oppName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.OPP_NAME
	 * 
	 * @param oppName
	 *            the value for FTZ_IN_TXN_DTL.OPP_NAME
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setOppName(String oppName) {
		this.oppName = oppName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.OPP_BANK_CODE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.OPP_BANK_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getOppBankCode() {
		return oppBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.OPP_BANK_CODE
	 * 
	 * @param oppBankCode
	 *            the value for FTZ_IN_TXN_DTL.OPP_BANK_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setOppBankCode(String oppBankCode) {
		this.oppBankCode = oppBankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.COUNTRY_CODE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.COUNTRY_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.COUNTRY_CODE
	 * 
	 * @param countryCode
	 *            the value for FTZ_IN_TXN_DTL.COUNTRY_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.DISITRICT_CODE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.DISITRICT_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getDisitrictCode() {
		return disitrictCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.DISITRICT_CODE
	 * 
	 * @param disitrictCode
	 *            the value for FTZ_IN_TXN_DTL.DISITRICT_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setDisitrictCode(String disitrictCode) {
		this.disitrictCode = disitrictCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.TRAN_TYPE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.TRAN_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getTranType() {
		return tranType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.TRAN_TYPE
	 * 
	 * @param tranType
	 *            the value for FTZ_IN_TXN_DTL.TRAN_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setTranType(String tranType) {
		this.tranType = tranType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.TERM_LENGTH
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.TERM_LENGTH
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public Short getTermLength() {
		return termLength;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.TERM_LENGTH
	 * 
	 * @param termLength
	 *            the value for FTZ_IN_TXN_DTL.TERM_LENGTH
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setTermLength(Short termLength) {
		this.termLength = termLength;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.TERM_UNIT
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.TERM_UNIT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getTermUnit() {
		return termUnit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.TERM_UNIT
	 * 
	 * @param termUnit
	 *            the value for FTZ_IN_TXN_DTL.TERM_UNIT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setTermUnit(String termUnit) {
		this.termUnit = termUnit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.VALUE_DATE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.VALUE_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getValueDate() {
		return valueDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.VALUE_DATE
	 * 
	 * @param valueDate
	 *            the value for FTZ_IN_TXN_DTL.VALUE_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setValueDate(String valueDate) {
		this.valueDate = valueDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.EXPIRE_DATE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.EXPIRE_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getExpireDate() {
		return expireDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.EXPIRE_DATE
	 * 
	 * @param expireDate
	 *            the value for FTZ_IN_TXN_DTL.EXPIRE_DATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setExpireDate(String expireDate) {
		this.expireDate = expireDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.INTEREST_RATE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.INTEREST_RATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public BigDecimal getInterestRate() {
		return interestRate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.INTEREST_RATE
	 * 
	 * @param interestRate
	 *            the value for FTZ_IN_TXN_DTL.INTEREST_RATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setInterestRate(BigDecimal interestRate) {
		this.interestRate = interestRate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.ISSUE_AMOUNT
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.ISSUE_AMOUNT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public BigDecimal getIssueAmount() {
		return issueAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.ISSUE_AMOUNT
	 * 
	 * @param issueAmount
	 *            the value for FTZ_IN_TXN_DTL.ISSUE_AMOUNT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setIssueAmount(BigDecimal issueAmount) {
		this.issueAmount = issueAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.ASSETS_TYPE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.ASSETS_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getAssetsType() {
		return assetsType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.ASSETS_TYPE
	 * 
	 * @param assetsType
	 *            the value for FTZ_IN_TXN_DTL.ASSETS_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setAssetsType(String assetsType) {
		this.assetsType = assetsType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.ASSETS_VALUE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.ASSETS_VALUE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public BigDecimal getAssetsValue() {
		return assetsValue;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.ASSETS_VALUE
	 * 
	 * @param assetsValue
	 *            the value for FTZ_IN_TXN_DTL.ASSETS_VALUE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setAssetsValue(BigDecimal assetsValue) {
		this.assetsValue = assetsValue;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.EXCHANGE_TYPE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.EXCHANGE_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getExchangeType() {
		return exchangeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.EXCHANGE_TYPE
	 * 
	 * @param exchangeType
	 *            the value for FTZ_IN_TXN_DTL.EXCHANGE_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setExchangeType(String exchangeType) {
		this.exchangeType = exchangeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.BUY_CURR
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.BUY_CURR
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getBuyCurr() {
		return buyCurr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.BUY_CURR
	 * 
	 * @param buyCurr
	 *            the value for FTZ_IN_TXN_DTL.BUY_CURR
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setBuyCurr(String buyCurr) {
		this.buyCurr = buyCurr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.BUY_AMT
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.BUY_AMT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public BigDecimal getBuyAmt() {
		return buyAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.BUY_AMT
	 * 
	 * @param buyAmt
	 *            the value for FTZ_IN_TXN_DTL.BUY_AMT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setBuyAmt(BigDecimal buyAmt) {
		this.buyAmt = buyAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.BUY_RATE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.BUY_RATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public BigDecimal getBuyRate() {
		return buyRate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.BUY_RATE
	 * 
	 * @param buyRate
	 *            the value for FTZ_IN_TXN_DTL.BUY_RATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setBuyRate(BigDecimal buyRate) {
		this.buyRate = buyRate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.SELL_CURR
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.SELL_CURR
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getSellCurr() {
		return sellCurr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.SELL_CURR
	 * 
	 * @param sellCurr
	 *            the value for FTZ_IN_TXN_DTL.SELL_CURR
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setSellCurr(String sellCurr) {
		this.sellCurr = sellCurr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.SELL_AMT
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.SELL_AMT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public BigDecimal getSellAmt() {
		return sellAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.SELL_AMT
	 * 
	 * @param sellAmt
	 *            the value for FTZ_IN_TXN_DTL.SELL_AMT
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setSellAmt(BigDecimal sellAmt) {
		this.sellAmt = sellAmt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.SELL_RATE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.SELL_RATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public BigDecimal getSellRate() {
		return sellRate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.SELL_RATE
	 * 
	 * @param sellRate
	 *            the value for FTZ_IN_TXN_DTL.SELL_RATE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setSellRate(BigDecimal sellRate) {
		this.sellRate = sellRate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.DOCUMENT_TYPE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.DOCUMENT_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getDocumentType() {
		return documentType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.DOCUMENT_TYPE
	 * 
	 * @param documentType
	 *            the value for FTZ_IN_TXN_DTL.DOCUMENT_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.DOCUMENT_NO
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.DOCUMENT_NO
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getDocumentNo() {
		return documentNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.DOCUMENT_NO
	 * 
	 * @param documentNo
	 *            the value for FTZ_IN_TXN_DTL.DOCUMENT_NO
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setDocumentNo(String documentNo) {
		this.documentNo = documentNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.LOAN_TYPE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.LOAN_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getLoanType() {
		return loanType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.LOAN_TYPE
	 * 
	 * @param loanType
	 *            the value for FTZ_IN_TXN_DTL.LOAN_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setLoanType(String loanType) {
		this.loanType = loanType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.OVERDUE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.OVERDUE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getOverdue() {
		return overdue;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.OVERDUE
	 * 
	 * @param overdue
	 *            the value for FTZ_IN_TXN_DTL.OVERDUE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setOverdue(String overdue) {
		this.overdue = overdue;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.SECURITIES_TYPE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.SECURITIES_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getSecuritiesType() {
		return securitiesType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.SECURITIES_TYPE
	 * 
	 * @param securitiesType
	 *            the value for FTZ_IN_TXN_DTL.SECURITIES_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setSecuritiesType(String securitiesType) {
		this.securitiesType = securitiesType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.SECURITIES_CODE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.SECURITIES_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getSecuritiesCode() {
		return securitiesCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.SECURITIES_CODE
	 * 
	 * @param securitiesCode
	 *            the value for FTZ_IN_TXN_DTL.SECURITIES_CODE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setSecuritiesCode(String securitiesCode) {
		this.securitiesCode = securitiesCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.OPP_CUS_TYPE
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.OPP_CUS_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getOppCusType() {
		return oppCusType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.OPP_CUS_TYPE
	 * 
	 * @param oppCusType
	 *            the value for FTZ_IN_TXN_DTL.OPP_CUS_TYPE
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setOppCusType(String oppCusType) {
		this.oppCusType = oppCusType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.CHK_STATUS
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.CHK_STATUS
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getChkStatus() {
		return chkStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.CHK_STATUS
	 * 
	 * @param chkStatus
	 *            the value for FTZ_IN_TXN_DTL.CHK_STATUS
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setChkStatus(String chkStatus) {
		this.chkStatus = chkStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.RSV1
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.RSV1
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getRsv1() {
		return rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.RSV1
	 * 
	 * @param rsv1
	 *            the value for FTZ_IN_TXN_DTL.RSV1
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setRsv1(String rsv1) {
		this.rsv1 = rsv1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.RSV2
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.RSV2
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getRsv2() {
		return rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.RSV2
	 * 
	 * @param rsv2
	 *            the value for FTZ_IN_TXN_DTL.RSV2
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setRsv2(String rsv2) {
		this.rsv2 = rsv2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column FTZ_IN_TXN_DTL.RSV3
	 * 
	 * @return the value of FTZ_IN_TXN_DTL.RSV3
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public String getRsv3() {
		return rsv3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column FTZ_IN_TXN_DTL.RSV3
	 * 
	 * @param rsv3
	 *            the value for FTZ_IN_TXN_DTL.RSV3
	 * 
	 * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
	 */
	public void setRsv3(String rsv3) {
		this.rsv3 = rsv3;
	}

	public String getMakUserId() {
		return makUserId;
	}

	public void setMakUserId(String makUserId) {
		this.makUserId = makUserId;
	}

	public String getMakDatetime() {
		return makDatetime;
	}

	public void setMakDatetime(String makDatetime) {
		this.makDatetime = makDatetime;
	}

	public String getChkUserId() {
		return chkUserId;
	}

	public void setChkUserId(String chkUserId) {
		this.chkUserId = chkUserId;
	}

	public String getChkDatetime() {
		return chkDatetime;
	}

	public void setChkDatetime(String chkDatetime) {
		this.chkDatetime = chkDatetime;
	}

	public String getChkAddWord() {
		return chkAddWord;
	}

	public void setChkAddWord(String chkAddWord) {
		this.chkAddWord = chkAddWord;
	}

	public String getOppBankName() {
		return oppBankName;
	}

	public void setOppBankName(String oppBankName) {
		this.oppBankName = oppBankName;
	}

	private String chkStatuss;

	public String getChkStatuss() {
		return chkStatuss;
	}

	public void setChkStatuss(String chkStatuss) {
		this.chkStatuss = chkStatuss;
	}

	public String getDtlSendStatus() {
		return dtlSendStatus;
	}

	public void setDtlSendStatus(String dtlSendStatus) {
		this.dtlSendStatus = dtlSendStatus;
	}
	
	public int getCdCount() {
		return cdCount;
	}

	public void setCdCount(int cdCount) {
		this.cdCount = cdCount;
	}

	public BigDecimal getCdSum() {
		return cdSum;
	}

	public void setCdSum(BigDecimal cdSum) {
		this.cdSum = cdSum;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();

		MessagesUtil message = MessagesUtil.getInstance();

		sb.append(message.getMessage("ftz.label.MSG_ID"))
				.append(CommonConst.SEPARATE_KEY_VALUE).append(this.getMsgId())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.SEQ_NO"))
				.append(CommonConst.SEPARATE_KEY_VALUE).append(this.getSeqNo())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.CD_FLAG"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getCdFlag())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.TRAN_DATE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getTranDate())
				.append(CommonConst.SEPARATE_TWO_FIELD)

				.append(message.getMessage("ftz.label.ACC_ORG_CODE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getAccOrgCode())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.ORG_TRAN_DATE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getOrgTranDate())
				.append(CommonConst.SEPARATE_TWO_FIELD)

				.append(message.getMessage("ftz.label.AMOUNT"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getAmount())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.OPP_NAME"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getOppName())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.OPP_ACCOUNT"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getOppAccount())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.OPP_BANK_NAME"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getOppBankName())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.OPP_BANK_CODE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getOppBankCode())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.COUNTRY_CODE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getCountryCode())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.DISTRICT_CODE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getDisitrictCode())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.TRAN_TYPE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getTranType())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.TERM_LENGTH"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getTermLength())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.TERM_UNIT"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getTermUnit())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.VALUE_DATE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getValueDate())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.EXPIRE_DATE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getExpireDate())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.INTEREST_RATE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getInterestRate())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.ISSUE_AMOUNT"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getIssueAmount())
				.append(CommonConst.SEPARATE_TWO_FIELD)

				.append(message.getMessage("ftz.label.ASSETS_VALUE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getAssetsValue())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.ASSETS_TYPE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getAssetsType())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.EXCHANGE_TYPE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getExchangeType())
				.append(CommonConst.SEPARATE_TWO_FIELD)

				.append(message.getMessage("ftz.label.BUY_CURR"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getBuyCurr())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.BUY_AMT"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getBuyAmt())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.BUY_RATE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getBuyRate())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.SELL_CURR"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getSellCurr())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.SELL_AMT"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getSellAmt())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.SELL_RATE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getSellRate())
				.append(CommonConst.SEPARATE_TWO_FIELD)

				.append(message.getMessage("ftz.label.DOCUMENT_NO"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getDocumentNo())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.DOCUMENT_TYPE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getDocumentType())
				.append(CommonConst.SEPARATE_TWO_FIELD)

				.append(message.getMessage("ftz.label.LOAN_TYPE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getLoanType())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.OVERDUE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getOverdue())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.SECURITIES_CODE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getSecuritiesCode())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.SECURITIES_TYPE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getSecuritiesType())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.OPP_CUS_TYPE"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getOppCusType())
				.append(CommonConst.SEPARATE_TWO_FIELD)

				.append(message.getMessage("ftz.label.CHK_STATUS"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(this.getChkStatus())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.MAK_USER_ID"))
				.append(CommonConst.SEPARATE_KEY_VALUE).append(getMakUserId())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.MAK_DATETIME"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(getMakDatetime())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.CHK_USER_ID"))
				.append(CommonConst.SEPARATE_KEY_VALUE).append(getChkUserId())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.CHK_DATETIME"))
				.append(CommonConst.SEPARATE_KEY_VALUE)
				.append(getChkDatetime())
				.append(CommonConst.SEPARATE_TWO_FIELD)
				.append(message.getMessage("ftz.label.CHK_ADD_WORD"))
				.append(CommonConst.SEPARATE_KEY_VALUE).append(getChkAddWord())
				.append(CommonConst.SEPARATE_TWO_FIELD);

		return sb.toString();
	}

}