package com.synesoft.ftzmis.domain.model;

public class FtzOffTxnDtlKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_TXN_DTL.MSG_ID
     *
     * @abatorgenerated Tue Jan 28 16:12:01 CST 2014
     */
    private String msgId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_TXN_DTL.SEQ_NO
     *
     * @abatorgenerated Tue Jan 28 16:12:01 CST 2014
     */
    private String seqNo;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_TXN_DTL.MSG_ID
     *
     * @return the value of FTZ_OFF_TXN_DTL.MSG_ID
     *
     * @abatorgenerated Tue Jan 28 16:12:01 CST 2014
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_TXN_DTL.MSG_ID
     *
     * @param msgId the value for FTZ_OFF_TXN_DTL.MSG_ID
     *
     * @abatorgenerated Tue Jan 28 16:12:01 CST 2014
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_TXN_DTL.SEQ_NO
     *
     * @return the value of FTZ_OFF_TXN_DTL.SEQ_NO
     *
     * @abatorgenerated Tue Jan 28 16:12:01 CST 2014
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_TXN_DTL.SEQ_NO
     *
     * @param seqNo the value for FTZ_OFF_TXN_DTL.SEQ_NO
     *
     * @abatorgenerated Tue Jan 28 16:12:01 CST 2014
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo;
    }
}