package com.synesoft.sysrunner.domain.model;

import java.math.BigDecimal;

public class BatStepRtmKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_RTM.RUNTIME_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private BigDecimal runtimeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_STEP_RTM.STEP_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private String stepId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_RTM.RUNTIME_ID
     *
     * @return the value of BAT_STEP_RTM.RUNTIME_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public BigDecimal getRuntimeId() {
        return runtimeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_RTM.RUNTIME_ID
     *
     * @param runtimeId the value for BAT_STEP_RTM.RUNTIME_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setRuntimeId(BigDecimal runtimeId) {
        this.runtimeId = runtimeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_STEP_RTM.STEP_ID
     *
     * @return the value of BAT_STEP_RTM.STEP_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getStepId() {
        return stepId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_STEP_RTM.STEP_ID
     *
     * @param stepId the value for BAT_STEP_RTM.STEP_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setStepId(String stepId) {
        this.stepId = stepId;
    }
}