package com.synesoft.sysrunner.domain.model;

public class BatTaskDimKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_TASK_DIM.DIMENSION_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private String dimensionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_TASK_DIM.DIM_TYPE_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private String dimTypeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column BAT_TASK_DIM.TASK_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    private String taskId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_TASK_DIM.DIMENSION_ID
     *
     * @return the value of BAT_TASK_DIM.DIMENSION_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getDimensionId() {
        return dimensionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_TASK_DIM.DIMENSION_ID
     *
     * @param dimensionId the value for BAT_TASK_DIM.DIMENSION_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setDimensionId(String dimensionId) {
        this.dimensionId = dimensionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_TASK_DIM.DIM_TYPE_ID
     *
     * @return the value of BAT_TASK_DIM.DIM_TYPE_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getDimTypeId() {
        return dimTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_TASK_DIM.DIM_TYPE_ID
     *
     * @param dimTypeId the value for BAT_TASK_DIM.DIM_TYPE_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setDimTypeId(String dimTypeId) {
        this.dimTypeId = dimTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column BAT_TASK_DIM.TASK_ID
     *
     * @return the value of BAT_TASK_DIM.TASK_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column BAT_TASK_DIM.TASK_ID
     *
     * @param taskId the value for BAT_TASK_DIM.TASK_ID
     *
     * @abatorgenerated Thu Dec 05 17:02:49 CST 2013
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
}