package com.synesoft.ftzmis.domain.model;

import org.hibernate.validator.constraints.NotEmpty;

import com.synesoft.fisp.app.common.utils.MessagesUtil;
import com.synesoft.ftzmis.app.common.constants.CommonConst;
import com.synesoft.ftzmis.app.model.FTZ210302Form.FTZ210302FormAddDtl;

public class FtzOffMsgCtl {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.MSG_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String msgId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.BRANCH_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String branchId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.VER
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String ver;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.SRC
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String src;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.DES
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String des;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.APP
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String app;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.MSG_NO
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String msgNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.MSG_REF
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String msgRef;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.WORK_DATE
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    @NotEmpty(groups = {FTZ210302FormAddDtl.class}, message = "{e.ftzmis.210302.0002}")
    private String workDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.EDIT_FLAG
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String editFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.RESERVE
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String reserve;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.RESULT
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String result;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.ADD_WORD
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String addWord;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.MSG_STATUS
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String msgStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.MAK_USER_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String makUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.MAK_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String makDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.CHK_USER_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String chkUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.CHK_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String chkDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.SND_USER_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String sndUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.SND_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String sndDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.ACK_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String ackDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.ERR_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String errDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.RSV1
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String rsv1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.RSV2
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String rsv2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FTZ_OFF_MSG_CTL.RSV3
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    private String rsv3;
    
    /** 报文状态组 */
    private String[] msgStatuss;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.MSG_ID
     *
     * @return the value of FTZ_OFF_MSG_CTL.MSG_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.MSG_ID
     *
     * @param msgId the value for FTZ_OFF_MSG_CTL.MSG_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.BRANCH_ID
     *
     * @return the value of FTZ_OFF_MSG_CTL.BRANCH_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.BRANCH_ID
     *
     * @param branchId the value for FTZ_OFF_MSG_CTL.BRANCH_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.VER
     *
     * @return the value of FTZ_OFF_MSG_CTL.VER
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getVer() {
        return ver;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.VER
     *
     * @param ver the value for FTZ_OFF_MSG_CTL.VER
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setVer(String ver) {
        this.ver = ver;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.SRC
     *
     * @return the value of FTZ_OFF_MSG_CTL.SRC
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.SRC
     *
     * @param src the value for FTZ_OFF_MSG_CTL.SRC
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setSrc(String src) {
        this.src = src;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.DES
     *
     * @return the value of FTZ_OFF_MSG_CTL.DES
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.DES
     *
     * @param des the value for FTZ_OFF_MSG_CTL.DES
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setDes(String des) {
        this.des = des;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.APP
     *
     * @return the value of FTZ_OFF_MSG_CTL.APP
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.APP
     *
     * @param app the value for FTZ_OFF_MSG_CTL.APP
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setApp(String app) {
        this.app = app;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.MSG_NO
     *
     * @return the value of FTZ_OFF_MSG_CTL.MSG_NO
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getMsgNo() {
        return msgNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.MSG_NO
     *
     * @param msgNo the value for FTZ_OFF_MSG_CTL.MSG_NO
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setMsgNo(String msgNo) {
        this.msgNo = msgNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.MSG_REF
     *
     * @return the value of FTZ_OFF_MSG_CTL.MSG_REF
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getMsgRef() {
        return msgRef;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.MSG_REF
     *
     * @param msgRef the value for FTZ_OFF_MSG_CTL.MSG_REF
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setMsgRef(String msgRef) {
        this.msgRef = msgRef;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.WORK_DATE
     *
     * @return the value of FTZ_OFF_MSG_CTL.WORK_DATE
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.WORK_DATE
     *
     * @param workDate the value for FTZ_OFF_MSG_CTL.WORK_DATE
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setWorkDate(String workDate) {
        this.workDate = workDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.EDIT_FLAG
     *
     * @return the value of FTZ_OFF_MSG_CTL.EDIT_FLAG
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getEditFlag() {
        return editFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.EDIT_FLAG
     *
     * @param editFlag the value for FTZ_OFF_MSG_CTL.EDIT_FLAG
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setEditFlag(String editFlag) {
        this.editFlag = editFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.RESERVE
     *
     * @return the value of FTZ_OFF_MSG_CTL.RESERVE
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getReserve() {
        return reserve;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.RESERVE
     *
     * @param reserve the value for FTZ_OFF_MSG_CTL.RESERVE
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setReserve(String reserve) {
        this.reserve = reserve;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.RESULT
     *
     * @return the value of FTZ_OFF_MSG_CTL.RESULT
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.RESULT
     *
     * @param result the value for FTZ_OFF_MSG_CTL.RESULT
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.ADD_WORD
     *
     * @return the value of FTZ_OFF_MSG_CTL.ADD_WORD
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getAddWord() {
        return addWord;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.ADD_WORD
     *
     * @param addWord the value for FTZ_OFF_MSG_CTL.ADD_WORD
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setAddWord(String addWord) {
        this.addWord = addWord;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.MSG_STATUS
     *
     * @return the value of FTZ_OFF_MSG_CTL.MSG_STATUS
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getMsgStatus() {
        return msgStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.MSG_STATUS
     *
     * @param msgStatus the value for FTZ_OFF_MSG_CTL.MSG_STATUS
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setMsgStatus(String msgStatus) {
        this.msgStatus = msgStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.MAK_USER_ID
     *
     * @return the value of FTZ_OFF_MSG_CTL.MAK_USER_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getMakUserId() {
        return makUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.MAK_USER_ID
     *
     * @param makUserId the value for FTZ_OFF_MSG_CTL.MAK_USER_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setMakUserId(String makUserId) {
        this.makUserId = makUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.MAK_DATETIME
     *
     * @return the value of FTZ_OFF_MSG_CTL.MAK_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getMakDatetime() {
        return makDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.MAK_DATETIME
     *
     * @param makDatetime the value for FTZ_OFF_MSG_CTL.MAK_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setMakDatetime(String makDatetime) {
        this.makDatetime = makDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.CHK_USER_ID
     *
     * @return the value of FTZ_OFF_MSG_CTL.CHK_USER_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getChkUserId() {
        return chkUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.CHK_USER_ID
     *
     * @param chkUserId the value for FTZ_OFF_MSG_CTL.CHK_USER_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setChkUserId(String chkUserId) {
        this.chkUserId = chkUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.CHK_DATETIME
     *
     * @return the value of FTZ_OFF_MSG_CTL.CHK_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getChkDatetime() {
        return chkDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.CHK_DATETIME
     *
     * @param chkDatetime the value for FTZ_OFF_MSG_CTL.CHK_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setChkDatetime(String chkDatetime) {
        this.chkDatetime = chkDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.SND_USER_ID
     *
     * @return the value of FTZ_OFF_MSG_CTL.SND_USER_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getSndUserId() {
        return sndUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.SND_USER_ID
     *
     * @param sndUserId the value for FTZ_OFF_MSG_CTL.SND_USER_ID
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setSndUserId(String sndUserId) {
        this.sndUserId = sndUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.SND_DATETIME
     *
     * @return the value of FTZ_OFF_MSG_CTL.SND_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getSndDatetime() {
        return sndDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.SND_DATETIME
     *
     * @param sndDatetime the value for FTZ_OFF_MSG_CTL.SND_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setSndDatetime(String sndDatetime) {
        this.sndDatetime = sndDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.ACK_DATETIME
     *
     * @return the value of FTZ_OFF_MSG_CTL.ACK_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getAckDatetime() {
        return ackDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.ACK_DATETIME
     *
     * @param ackDatetime the value for FTZ_OFF_MSG_CTL.ACK_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setAckDatetime(String ackDatetime) {
        this.ackDatetime = ackDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.ERR_DATETIME
     *
     * @return the value of FTZ_OFF_MSG_CTL.ERR_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getErrDatetime() {
        return errDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.ERR_DATETIME
     *
     * @param errDatetime the value for FTZ_OFF_MSG_CTL.ERR_DATETIME
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setErrDatetime(String errDatetime) {
        this.errDatetime = errDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.RSV1
     *
     * @return the value of FTZ_OFF_MSG_CTL.RSV1
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getRsv1() {
        return rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.RSV1
     *
     * @param rsv1 the value for FTZ_OFF_MSG_CTL.RSV1
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setRsv1(String rsv1) {
        this.rsv1 = rsv1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.RSV2
     *
     * @return the value of FTZ_OFF_MSG_CTL.RSV2
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getRsv2() {
        return rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.RSV2
     *
     * @param rsv2 the value for FTZ_OFF_MSG_CTL.RSV2
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setRsv2(String rsv2) {
        this.rsv2 = rsv2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FTZ_OFF_MSG_CTL.RSV3
     *
     * @return the value of FTZ_OFF_MSG_CTL.RSV3
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public String getRsv3() {
        return rsv3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FTZ_OFF_MSG_CTL.RSV3
     *
     * @param rsv3 the value for FTZ_OFF_MSG_CTL.RSV3
     *
     * @abatorgenerated Wed Dec 25 11:25:40 CST 2013
     */
    public void setRsv3(String rsv3) {
        this.rsv3 = rsv3;
    }

	/**
	 * @return the msgStatuss
	 */
	public String[] getMsgStatuss() {
		return msgStatuss;
	}

	/**
	 * @param msgStatuss the msgStatuss to set
	 */
	public void setMsgStatuss(String[] msgStatuss) {
		this.msgStatuss = msgStatuss;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();

		MessagesUtil message = MessagesUtil.getInstance();
		
		sb.append(message.getMessage("ftz.label.MSG_ID")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getMsgId()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.common.branchId")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getBranchId()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.VER")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getVer()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.SRC")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getSrc()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.DES")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getDes()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.APP")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getApp()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.MSG_NO")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getMsgNo()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.MSG_REF")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getMsgRef()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.WORK_DATE")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getWorkDate()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.EDIT_FLAG")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getEditFlag()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.RESERVE")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getReserve()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.RESULT")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getResult()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.ADD_WORD")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getAddWord()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.MSG_STATUS")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getMsgStatus()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.MAK_DATETIME")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getMakDatetime()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.MAK_USER_ID")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getMakUserId()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.CHK_DATETIME")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getChkDatetime()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.CHK_USER_ID")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getChkUserId()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.SND_DATETIME")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getSndDatetime()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.SND_USER_ID")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getSndUserId()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.ACK_DATETIME")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getAckDatetime()).append(CommonConst.SEPARATE_TWO_FIELD)
			.append(message.getMessage("ftz.label.ERR_DATETIME")).append(CommonConst.SEPARATE_KEY_VALUE).append(this.getErrDatetime()).append(CommonConst.SEPARATE_TWO_FIELD);
		
		return sb.toString();
	}
	
	
}